### ISSUE TITLE
Showing Points and Polylines

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#10]
Is it possible to show points and polyline data via the addGeoJSON method (with or without height attribute) on the GL / OSM map? 

What I am trying to do is show buildings with height, in conjunction with lines (without height). Per my testing, Lines or points cannot be displayed and the geoJSON should contain polygon only.

**Comment by hrishiballal** [comment]
Closing issue, I am going to try using https://github.com/kekscom/L.Line3 to see if it works that way.

**Comment by kekscom** [comment]
All findings are correct.
For 2.5D on Leaflet it's easy to solve.
For pure WebGL things are difficult as you might need some 3D lib for that. OSM Buildings WebGL will also be available on Leaflet soon. Maybe that helps.
