### ISSUE TITLE
How can we create a suitable geojson for OSMBuilding in postgis

### ISSUE THREAD

**Issue by am2222** [OSMBuildings/OSMBuildings#100]
Hi,
has any one ever tried to export result of a postgis query in geojson which is suitable to use as input in osmbuilding?
I have color and hight properties in my table,what other parameters should I have in table?
thanks

**Comment by am2222** [comment]
It seems that I can also load geojson form geoserver,It will be great if I can use it with OSMbuilding

http://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html

**Comment by am2222** [comment]
well..I find out how to do it..thanks

**Comment by kekscom** [comment]
Should be easy to provide GeoJSON.
Here's some more information: https://github.com/OSMBuildings/OSMBuildings/blob/master/docs/server.md
