### ISSUE TITLE
Map goes blank if zoomed in or out

### ISSUE THREAD

**Issue by PedroD** [OSMBuildings/OSMBuildings#101]
Hi!

I was trying your map, and I've found a strange behavior.

In [this](http://codepen.io/osmbuildings/pen/avXGJy) example if you zoom out to the limit, the screen will go blank.

In your `dist/index.html` example of this repository, if you zoom in or zoom out enough you will also see the blank screen.

Is this a bug? How do I avoid the user to go beyond these zoom thresholds (even with the mouse wheel)?

Thanks! Best map library ever!

**Comment by kekscom** [comment]
Hi,
This is all as desired. Look at the code, there are 2 places for controlling the map's minZoom and the building's minZoom. Just change the values.
Be aware zoom less than 14 could make buildings very slow.

**Comment by PedroD** [comment]
Hello, thanks for answering!

I have notice those parameters ([this one correct?](http://image.prntscr.com/image/1ead95546e704cc1a2d4cca51a1e6619.png)).

However that only decides when the blank screen will appear.

That code excerpt came from the example located in the `dist` folder of the OSMBuildings repository, if you open it and, independently of the values you provide to `minZoom` and `maxZoom`, you will notice that the screen goes blank if you zoom in or out beyond the limits you provide.

Previous versions of the map would just stop zooming when the limits were reached, but this version keeps on zooming in/out beyond the limits, but with a blank screen.

**Comment by kekscom** [comment]
You're referring to the latest code. Fine so far.
So there should be a distinction between buildings min/max zoom for rendering and map min/max zoom for interaction. Correct?

I'd tend to hard code buildings and let the user decide about the map.

**Comment by PedroD** [comment]
I think so, it seems that the map stops rendering after those boundaries, but the zoom interaction carries on, so even when the screen goes blank I can keep on zooming in and out.

I wouldn't say create a distinction, I guess it is just the zooming scroll should get disabled if the user keeps trying to zoom beyond the limit.

**Comment by kekscom** [comment]
fixed
