### ISSUE TITLE
No buildings on HTTPS (Chrome blocks mixed content by default)

### ISSUE THREAD

**Issue by Piskvor** [OSMBuildings/OSMBuildings#103]
- have Chrome 51.0.2704.103 m
- go to http://osmbuildings.org/
- see the tower - this is expected behavior

- go to https://osmbuildings.org/
- no tower, just the basemap - this is the issue
- see multiple errors in JS Console: 
`map.js:8 Mixed Content: The page at 'https://osmbuildings.org/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://a.data.osmbuildings.org/0.2/ph2apjye/tile/15/17606/10746.json'. This request has been blocked; the content must be served over HTTPS.`
- not even allowing insecure requests (shield icon in address bar) helps

Since searching for "Osm Buildings" often gives the HTTPS version in results, visitor is left scratching his head; would it be possible to provide a HTTPS version for the GeoJSON tiles?
Thank you.

**Comment by kekscom** [comment]
Good point!

**Comment by Piskvor** [comment]
I seem to break stuff with my mere presence ;)
Anyway, check https://github.com/osmcz/osmcz/issues/129 for ideas - the technical mitigation should be clear enough despite the language.

**Comment by kekscom** [comment]
I've changed protocols for https.
