### ISSUE TITLE
Feed Geojson URL by geoserver vector tile

### ISSUE THREAD

**Issue by am2222** [OSMBuildings/OSMBuildings#105]
Hi,
Is it possible to feed osmbuilding with geoserver vector tile service?Does any one ever tried?

**Comment by kekscom** [comment]
If data is valid GeoJSON, it should work.

**Comment by am2222** [comment]
Geo server shares a valid GeoJSON but I'm afraid that it does not share in this format
`  DATA_SRC = 'http://{s}.data.osmbuildings.org/0.2/{k}/tile/{z}/{x}/{y}.json',`
I think it shares other formats than this

**Comment by kekscom** [comment]
That's TMS. I think GeoServer should be able to provide that.
If you have examples of URLs and content, please add them here.

**Comment by am2222** [comment]
I am yet searching,I'll share the results here..thanks

**Comment by am2222** [comment]
this is an example of Geojson vector tile which is provided by geoserver
`http://127.0.0.1:8080/geoserver/indoor/wms?service=WMS&version=1.1.0&request=GetMap&layers=indoor:in2&styles=&bbox=51.3591346740723,32.6179275512695,51.359317779541,32.6181678771973&width=585&height=768&srs=EPSG:4326&format=application%2Fjson%3Btype%3Dgeojson`

**Comment by kekscom** [comment]
I see the URL. Maybe there is a WMTS option.
Content is clearly not reachable for me :-)

**Comment by am2222** [comment]
@kekscom I have found that if we use geoserver with geowebcatch we can serve TMS ,[This ](http://geowebcache.org/docs/current/services/tms.html) is  its documention 
It seems we can server this format
`http://127.0.0.1:8080/geoserver/gwc/service/tms/1.0.0/indoor%3Ain2@EPSG%3A4326@geojson/0/0/1.json`
so this may work
`DATA_SRC = 'http://{s}.data.osmbuildings.org/0.2/{k}/tile/{z}/{x}/{y}.json',`
but what is k?does we must serve k too?

**Comment by kekscom** [comment]
{k} is for a key if requiried. You can just omit it.

**Comment by am2222** [comment]
so it seems we have some chances to serve from geoserver and it is great..
