### ISSUE TITLE
Openlayer 3 rotation

### ISSUE THREAD

**Issue by am2222** [OSMBuildings/OSMBuildings#106]
Hi,
I have tried to add osmbuilding into this [geolocation orientation openlayer3,](http://openlayers.org/en/latest/examples/geolocation-orientation.html)
every thing works fine except rotation.as map rotates the buildings doe not follow rotation. Is there any way to fix it?

**Comment by am2222** [comment]
any ideas?

**Comment by kekscom** [comment]
Still, OL3 support is just rough.
If you could setup a CodePen, I could give some advice.

**Comment by am2222** [comment]
I could not setup CodePen I had too add some extra js libraries..
Can you check the code on this site?
http://gfpishro.ir/osm/

but I noticed that osmbuilding server gives 504 error now

**Comment by kekscom** [comment]
Good we had this test.
You're using the 2.5D version which just doesn't provide any rotation.
If you're really keen on hacking, you might modify all `project()` methods in the source code.
But I can't really recommend it.

Rotation might be a better option with the 3D version but I don't have an OL adapter yet.

**Comment by am2222** [comment]
@kekscom  thanks for your help,So you mean It it better to develope an OL adapter or sth like that?Is it possible to develope it?Can I do that ?

**Comment by kekscom** [comment]
Not sure whether you'll make it. However, we have something close to that in leaflet branch.
Will be lots of adaption.

**Comment by am2222** [comment]
thanks,I'll try to find how you have done in leaflet and if I can do it with openlayers,I am new with javascript and I hope I can manage to do it

**Comment by am2222** [comment]
@kekscom sorry,You mean this branch?
https://github.com/OSMBuildings/OSMBuildings/tree/leaflet/src/engines/Leaflet

**Comment by kekscom** [comment]
Exactly!
