### ISSUE TITLE
Loading the same model several times

### ISSUE THREAD

**Issue by JeremieLussiez** [OSMBuildings/OSMBuildings#107]
Good evening,

When I try to load the same model several times, only one is actually rendering.
I think the issue is related to the addObj caching mechanism because when I disable the **queue** object at **line 4705** of **OSMBuildings.debug.js**, [everything is rendered](https://cloud.githubusercontent.com/assets/2599874/17347798/6e01f092-5912-11e6-9ce3-b7d544ecbfaa.png). Maybe it would be better if it was the result of the request that is cached rather than the request.
Am I supposed to only load one instance of each model or is it a bug/wrong usage of the library ?
!

Thanks !

PS: By the way, great library :)
PS2: I saw your comment in your code about promises, yup, it could solve the problem as you would not end up with a cached pending request and trying to load something that is not existing yet ;)

**Comment by kekscom** [comment]
Hi! Could you make sure you are using the very latest release?
Exactly that issue has been solved a few days ago :-)

**Comment by JeremieLussiez** [comment]
You're right, my version was 3 weeks old, it's working with the latest one :)
Thank you !
