### ISSUE TITLE
Toggle OBJ objects

### ISSUE THREAD

**Issue by ramitix** [OSMBuildings/OSMBuildings#108]
HI,
Actually, I have couple questions .
1- How to toggle geojson tiles on\off and change it's color ?
    I tried with functions addLayer & removeLayer with no luck also setStyle function is DEPRECATED.

2- How to toggle added OBJs on\off ? 
    Same thing I tried with functions addLayer & removeLayer it will add it but won't remove it .

Thanks

**Comment by kekscom** [comment]
Hi!
1. There is no regular off, but you can try
~~~
var gj = osmb.addGeoJSON(...);
...
gj.destroy();
~~~

Currently there is no setStyle() but you can either cololor all objects with extra options in  `osmb.addGeoJSON(...)` or you can use the `featureloaded` event and change objects initially.

2. Same thing for OBJ.

**Comment by ramitix** [comment]
I want to load the OBJs  to work like geojson tiles to load only the ones in the view not all of them, I wanted to try to do it with bounds, add the ones in the camera view and destroy the rest ..is there an easy way to implement this idea?
Thanks

**Comment by kekscom** [comment]
You can get the current visible bounds with getBounds(). That should get you started.
I've fixed missing documentation for that.

**Comment by ramitix** [comment]
I will try it and let you know , Thanks Jan.
