### ISSUE TITLE
Panning maps on touch screen devices shifts the map before panning

### ISSUE THREAD

**Issue by jdgodchaux** [OSMBuildings/OSMBuildings#110]
Hello,

Using 3.1, I've found that when I try to pan maps on touch screen devices, the map shifts to the north or the northwest, or sometimes what seems like a random direction as soon as one touches the touch screen. Otherwise the map pans well when dragged after touching the screen. You can see this behavior by going to the [OSM Buildings homepage](http://osmbuildings.org/) on a touch screen device. 

Thanks for this great tool!!

**Comment by kekscom** [comment]
fixed

**Comment by jdgodchaux** [comment]
Wonderful! Thank you!
