### ISSUE TITLE
Filter GeoJSON Tiles

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#111]
GeoJSON tiles can be linked using the .addGeoJSONTiles method

I have a question regarding these tiles: If I place a custom object on the map and addGeoJSONTiles is enabled, the object from the server is rendered regardless of if there is a existing object on the map. Is there a way to filter these tiles if a object already exists on the map?

In the screenshot, the red buildings are added by me and the gray / white ones are requested using the .addgeojsontiles from the server. I would like to turn off the white ones. I am not sure if it can be done but just wanted to query. 

![overlapping](https://cloud.githubusercontent.com/assets/1588744/18351503/55c89d0a-75d2-11e6-9810-9ea921c013a9.png)

**Comment by kekscom** [comment]
I have a similar issue when replacing OSM objects by HD models.
There was a mechanism to manually turn off objects by id. It means you have a manual process selecting them once. 
I'm happy to restore that.
There could be also a collision check but I'm afraid it will be expensive.

**Comment by hrishiballal** [comment]
It would be great if objects were able to be turned off by ID. 

At the moment, I have the following : 
```javascript 
osmb.on('loadfeature', function(e) {
  // code to see if the feature is from GeoJSONtile server and within the bounds of objects generated by me. 
    });
```

But I cannot turn it off so this method will be great. Thanks!

**Comment by hrishiballal** [comment]
Hi @kekscom I was checking the API documentation and there is no way to remove added objects by ID, the collision check I can do on client side so I would need the ID and "bounds" of the object or GeoJSON of the object so check if it intersects and turn it off if it did. I guess in addition to delete by ID we should have "information by ID" as well. Not sure how expensive it is.

**Comment by kekscom** [comment]
Hi Hrishi, I would go for filtering objects.
~~~js
osmb.hide(feature => {
  return (featureIdsToHide.indexOf(feature.id) > -1); // hides if true
});
~~~

We will provide bounds as well in a bit. In order to save data I can imagine 2 points (min/max) or a center point + radius. Any preference?

**Comment by hrishiballal** [comment]
Hi Jan, 
Thank you for this, yes bounds work perfectly we generally deal with rectangles (polygons) not a radius but I can imagine that will work as well. 

I have a question to the suggestion above though: I can get the ID of the OSM feature but where can I get the geometry? I want to get the feature geometry check if it intersects my bounds and then hide it.

**Comment by kekscom** [comment]
Update: I've pushed functionality to get another property 'bounds' per event target.
It seems working but not an ideal fit because buildings are usually not aligned.

Minimal bounding box, convex hull or exact outline would work much better but also take a lot more resources.

Please have a look if current solution with bounds would fit your requirements.

**Comment by hrishiballal** [comment]
Thank you, I will check and report back.

**Comment by hrishiballal** [comment]
OK This works, pasting the sample code below. OSM has ID as integers and I have to check if there is a integer ID which means that the "building" is coming from OSMB and if it intersects the bounds (using Leaflet) I hide it. 

```javascript

    osmb.hide(feature => {
        const bounds = L.latLngBounds([feature.properties.bounds['min'][1], feature.properties.bounds['min'][0]],
            feature.properties.bounds['max'][1], feature.properties.bounds['max'][0]);
        if (mb.intersects(bounds) && Number.isInteger(parseInt(feature.id))) {
            return 1;

        } else {
            return 0;
        }
    });

```

**Comment by kekscom** [comment]
Using types do distinct from OSMB sounds scary :-D
However, great bounds are working.
Still assume it might be too imprecise for filtering.
Consider this feature to be beta.
