### ISSUE TITLE
Crashing when displaying a large amount of GeoJSON

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#113]
Is there a limit to the amount of GeoJSON that can be rendered using the library. When using Chrome for cases when there is a large amount of GeoJSON, the web page crashes.

**Comment by kekscom** [comment]
Memory is the only limit.
From a certain amount of data I'd rather split it into tiles. We did that for Berlins neue Skyline 2015 and there should be a script on GitHub.

**Comment by hrishiballal** [comment]
Can tiles be created on the fly in the browser? I am generating a lot of geojson in the browser.

**Comment by hrishiballal** [comment]
I think I got it. A bit of a hack but I will use Geojson vt on server and then do this.
