### ISSUE TITLE
Feature request: GeoJSON extrusion visual

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#114]
It would be nice if there was a option in the default extrusion mechanism to show floors. 

![etage1](https://cloud.githubusercontent.com/assets/1588744/18764909/53fa2fae-810b-11e6-92b6-47d1456ae8c2.png)

One floor is around 10 feet or 3.048 meters. So lines showing them would be nice. 

As a question: If I wanted to show such a effect how can I do it? 

Image source: https://en.wikipedia.org/wiki/Storey

**Comment by kekscom** [comment]
Quick and dirty would be adding as per many footprints with appropriate minHeight/height set.
A coded solution would technically do the same. 
But amount of data would be a multiple.

**Comment by Vishnupriyachirappa** [comment]
can u give code to change colors of buildings

**Comment by kekscom** [comment]
I'm closing this because the initial request will not get a reasonable elegant solution.
@Vishnupriyachirappa request will be dealt with in #148
