### ISSUE TITLE
Documentation always says 'url' even though code accepts objects

### ISSUE THREAD

**Issue by PeterVermont** [OSMBuildings/OSMBuildings#115]
The documention for several of the methods specify 'url but as the GeoJSON tutorial example shows, at least one of them can take a GeoJSON featurelist object.

https://osmbuildings.github.io/OSMBuildings/tutorial-GeoJSON.html

![image](https://cloud.githubusercontent.com/assets/889233/19003064/1fb6ab74-871d-11e6-8f0c-2a9665b61acb.png)

**Comment by kekscom** [comment]
Documentation updated. It should be published soon.
Thank you!

**Comment by PeterVermont** [comment]
Thanks for responding.
I know that the example was just for addGeoJSOn but the capability to handle collection objects is also in addGeoJSONTiles (via support in mesh.GeoJSON).

**Comment by kekscom** [comment]
You're right. It's because there is the same code in background.
So far I didn't see how to use GeoJSON object tiles. That's why no documentation.
Can you imagine a case?
