### ISSUE TITLE
layers animation

### ISSUE THREAD

**Issue by kosik** [OSMBuildings/OSMBuildings#117]
How to draw circle on top of the map? Like in this example: http://openlayers.org/en/latest/examples/draw-features.html

Many thanks in advance.

**Comment by kekscom** [comment]
The map approaches are very different.
If you want to have a circle visible, you have to calculate one on your own in geo coordinates.
Then make it GeoJSON and add it to the map.

What could make things easier is to create a rectangle in geo coordinates and set a property `shape:circle`.
