### ISSUE TITLE
Missing tiles in New York City

### ISSUE THREAD

**Issue by jdgodchaux** [OSMBuildings/OSMBuildings#118]
Hello!

Again, thank you all for the great tool! There appear to be two square-shaped (tiles?) sections in New York City where no buildings exist, though there are certainly buildings. On the Lower East Side here:
http://osmbuildings.org/?lat=40.708&lon=-73.99794&zoom=15&rotation=0&tilt=30

With these errors in the console:

```
map.js:1 Uncaught TypeError: Cannot read property 'offset_sec' of undefined updateLocationInfo @ map.js:1(anonymous function) @ map.js:9(anonymous function) @ script.js:1emit @ script.js:1b.onGeocode @ map.js:9c.onreadystatechange @ script.js:1
map.js:5 Uncaught Error: can't handle ridged roof geometry
```

And on the Upper East Side here:
http://osmbuildings.org/?lat=40.77377&lon=-73.95453&zoom=15&rotation=0&tilt=30

With these errors in the console:

```
map.js:8 GET https://a.data.osmbuildings.org/0.2/ph2apjye/tile/15/9652/12312.json 408 (Request Time-out)
```

Any help you can provide would be much appreciated!! Thank you!!

**Comment by kekscom** [comment]
Thanks for reporting.
Fix is in place.

**Comment by kekscom** [comment]
Sorry, two different topic. First case is solved.
For the latter, data size might be too big. I'll check.

**Comment by kekscom** [comment]
The latter doesn't occur anymore.

**Comment by jdgodchaux** [comment]
Thanks very much! Looks great!
