### ISSUE TITLE
roofColor not rendering properly

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#119]
In one of my GeoJSON we have the following color: [0a650c](http://www.beautycolorcode.com/0a650c). However when it is rendered it is renders as black. I am setting the roofColor and height property. Is there a reason why this happens?  

<img width="627" alt="blackrender" src="https://cloud.githubusercontent.com/assets/1588744/19702575/19f125e0-9af8-11e6-9cd4-bc63f3af0ba2.png">

**Comment by kekscom** [comment]
Did you forget the leading hash mark?

**Comment by hrishiballal** [comment]
I checked and following is my property object in GeoJSON, using console.log

Even with higher heights it is causing a issue. 

```json
{color: "#d0d0d0", roofColor: "#0a650c", height: 0.1}
```

**Comment by kekscom** [comment]
Could you paste me a GeoJSON snippet?

**Comment by hrishiballal** [comment]
[Gist](https://gist.githubusercontent.com/anonymous/5b6f8a8c20fd788e6841221e3a0d3818/raw/c69898c85b4743e8277763ba0ef4e6acc265c298/map.geojson)

**Comment by kekscom** [comment]
Thanks for the sample.
This issue relates to #48. Basically there is a vertical gradient which ignores building height.
So flat objects get very dark.

A quick and very ugly hack would be:

`.. "properties": { "height":50 .. } ..`
and
`osmb.addGeoJSON('test.json', { elevation:-49 });`

**Comment by kekscom** [comment]
fixed
