### ISSUE TITLE
Highlighting Multiple Buildings does not work any more with 3.1.0 release

### ISSUE THREAD

**Issue by mljolje** [OSMBuildings/OSMBuildings#120]
Example of how to Highlighting Multiple Buildings:

https://osmbuildings.github.io/OSMBuildings/tutorial-Highlighting%20Multiple%20Buildings.html

is not working anymore, i.e. all buildings are highlighted by default and when you select one/multiple building they disappear from map.

**Comment by kekscom** [comment]
I'll have a look.
Current solution is a hack and will not receive much attention.
