### ISSUE TITLE
Enable ability to show GeoJSON without extruding

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#121]
In our work, some GeoJSON polygons need not be extruded (but need to be displayed). I usually specify height as 0.01 or some low number. It would be nice if the library can render GeoJSON that is flat with the standard geoJSON [styling](http://leafletjs.com/reference-1.0.0.html#path-option). 

The most important thing for me is to enable rendering / adding of transperent, non-extruded geoJSON.

**Comment by kekscom** [comment]
From what I see, 0 does it as well. Which is a bit cleaner.
However I need to tell part undefined height in buildings from flat GeoJSON.
Undefined buildings heights default to some value to keep things useful.
As common case is buildings It'S fair to ask for a height:0 on flat GeoJSON.

**Comment by hrishiballal** [comment]
Yes agreed. If setting height:0 is the "recommended" way to show a flat geoJSON. I would like to request enabling transparency for flat geoJSONs. One of the main reasons, I use height:0 is to show a flat polygon and it is important for the user to see what is "underneath" it.

**Comment by kekscom** [comment]
For transparency #31 is the right place. Complexity is the same for flat objects.
