### ISSUE TITLE
Destroying OSMB object triggers endless exceptions

### ISSUE THREAD

**Issue by mljolje** [OSMBuildings/OSMBuildings#122]
Destroying OSMB object triggers endless exceptions below:

After calling:
`osmb.destroy();`

getting:
`OSMBuildings.debug.js:6496 Uncaught TypeError: Cannot read property 'viewport' of undefined(…)onChange 
@ OSMBuildings.debug.js:6496renderFrame 
@ OSMBuildings.debug.js:6386
`

**Comment by kekscom** [comment]
Thanks for reporting.
I've pushed a fix to master branch.

**Comment by mljolje** [comment]
Thanks for quick fix.
What is proper way of destroying OSMBuilding object?
Only calling .destroy() method?
I am asking this when I destroy it and later create it again I am getting new type of problems:

`OSMBuildings.debug.js:535 WebGL: INVALID_OPERATION: bindBuffer: object not from this contextenable @ OSMBuildings.debug.js:535bindBuffer @ OSMBuildings.debug.js:747Ia.DepthFogNormalMap.render @ OSMBuildings.debug.js:7139renderFrame @ OSMBuildings.debug.js:6231
OSMBuildings.debug.js:535 WebGL: INVALID_OPERATION: bindBuffer: object not from this contextenable @ OSMBuildings.debug.js:535bindBuffer @ OSMBuildings.debug.js:747Ia.DepthFogNormalMap.render @ OSMBuildings.debug.js:7140renderFrame @ OSMBuildings.debug.js:6231`

and later again endless exceptions:

`OSMBuildings.debug.js:5992 Uncaught TypeError: Cannot read property '0' of undefined(…)B @ OSMBuildings.debug.js:5992C @ OSMBuildings.debug.js:6006onChange @ OSMBuildings.debug.js:6351renderFrame @ OSMBuildings.debug.js:6187
OSMBuildings.debug.js:5992 Uncaught TypeError: Cannot read property '0' of undefined(…)B @ OSMBuildings.debug.js:5992C @ OSMBuildings.debug.js:6006onChange @ OSMBuildings.debug.js:6351renderFrame @ OSMBuildings.debug.js:6187`

Thanks,

**Comment by kekscom** [comment]
I'd recommend calling destroy(). And don't try to revive the object. Start over.
For the errors I should see a running example.

**Comment by mljolje** [comment]
This part of code shows this issue (it is stupid one just to point issue):

`			// Create
			var osmb = new OSMBuildings(
					{
						position: { latitude:45.81484, longitude:13.41000 },
						zoom : 10,
						minZoom : 15,
						maxZoom : 22,
						effects : [ 'shadows' ],
						attribution : '© 3D <a href="https://osmbuildings.org/copyright/">OSM Buildings</a>'
					});

			osmb.appendTo(scope.mapId);
			osmb
					.addMapTiles(
							'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
							{
								attribution : '© Data <a href="http://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="http://mapbox.com">Mapbox</a>'
							});
			osmb
					.addGeoJSONTiles('http://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');

			// Destroy it
			osmb.destroy();
			
			// Create again
			osmb = new OSMBuildings(
					{
						position: { latitude:45.81484, longitude:13.41000 },
						zoom : 10,
						minZoom : 15,
						maxZoom : 22,
						effects : [ 'shadows' ],
						attribution : '© 3D <a href="https://osmbuildings.org/copyright/">OSM Buildings</a>'
					});

			osmb.appendTo(scope.mapId);
			osmb
					.addMapTiles(
							'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
							{
								attribution : '© Data <a href="http://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="http://mapbox.com">Mapbox</a>'
							});
			osmb
					.addGeoJSONTiles('http://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');`

**Comment by kekscom** [comment]
Ok I see. Solving this will be a bigger journey.
Please don't expect this soon.

**Comment by mljolje** [comment]
Thanks. :)

**Comment by mljolje** [comment]
I think that adding:

`data.Index.destroy();`

inside function:

`GLX.destroy`

resolves this issue.

**Comment by kekscom** [comment]
Interesting!
I'd rather put the line in src/index.js destroy()
Then there are issues with the sky and I think buffers are not really destroyed but rather unlinked.
