### ISSUE TITLE
Server URL questions (worldwind java integration)

### ISSUE THREAD

**Issue by sbodmer** [OSMBuildings/OSMBuildings#123]
Hi folks,
I'm trying to integrate OSM Buildings into Nasa Worldwind as a new layer.
When I look at the documentation for accessing the json data, the url is

  `http://a.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json`

There is no explanation for the {z} part (which I assume is the fixed zoom level).
Is the zoom level always fixed to 15 ?
If so, my calculation for a Geneva (CH) tile at lat 46.1935, lon 6.129 is
x=16942, y=24798, but nothing is returned for this url...
  
  `http://a.data.osmbuildings.org/0.2/anonymous/tile/15/16942/24798.json`

If I look the osmbuilding example web site, the url for a Geneva tile is

   `http://a.data.osmbuildings.org/0.2/ph2apjye/tile/15/16942/11630.json`

The {y} seems to be different, how to calculate the correct {y} part ?

Thanks for some feedback of any kind ;^)

**Comment by kekscom** [comment]
Hi,
Yes, z is a fixed zoom level. Not sure, how you've calculated the y position, but last url would give a correct result. Just replace it's key by `anonymous`: http://a.data.osmbuildings.org/0.2/anonymous/tile/15/16942/11630.json

```
// worldSize = 1 << zoom;
function project(latitude, longitude, worldSize) {
  var
    x = longitude/360 + 0.5,
    y = Math.min(1, Math.max(0, 0.5 - (Math.log(Math.tan((Math.PI/4) + (Math.PI/2)*latitude/180)) / Math.PI) / 2));
  return { x: x*worldSize, y: y*worldSize };
}


```

**Comment by sbodmer** [comment]
Thanks for the code sample, I forgot to do the mercator projection for the latitude.
