### ISSUE TITLE
JSDoc need corect

### ISSUE THREAD

**Issue by 7dir** [OSMBuildings/OSMBuildings#125]
[loadfeature 2 times](https://github.com/OSMBuildings/OSMBuildings/search?utf8=%E2%9C%93&q=loadfeature++Fired+when+a+3d+object+has+been+loaded&type=Code)

**Comment by kekscom** [comment]
From what I see this is correct.

**Comment by 7dir** [comment]
@kekscom 
but why there is [2 times in JSDoc](https://osmbuildings.github.io/OSMBuildings/OSMBuildings.html) ?



```
Events
...
idle
Fired when data loading ends

loadfeature
Fired when a 3d object has been loaded

loadfeature
Fired when a 3d object has been loaded

resize
Fired when the map is resized
...
```

**Comment by kekscom** [comment]
Ok I see.
Made some corrections in JSDoc tagging but it still happens.
From what I found there are some issues in JSDoc itself.
For now I'm not going to dig deeper into that.

**Comment by 7dir** [comment]
So you can add some label **Docs**
docs is terrable - sorry
