### ISSUE TITLE
Touch screen 'touchstart' not working as expected.

### ISSUE THREAD

**Issue by jdgodchaux** [OSMBuildings/OSMBuildings#127]
Hello!

Again, thank you for this excellent library! I'm having trouble with touch events on mobile devices, specifically with the `'touchstart'` event. In a function scoped as `osmApplication`, I'm trying to fire a `'touchstart'` event like this:

```
    osmApplication.osmb.on('touchstart', function(e) {
        var xcoor = e.touches[0].clientX;
        var ycoor = e.touches[0].clientY;
        osmApplication.onClick(xcoor, ycoor);
    });
```

`osmApplication.onClick` reveals a hidden div positioned near the click with data from the properties of a GeoJSON loaded with the `addGeoJSON` method. The problem I'm running into is that when I run `osmApplication.onClick` with the `'touchstart'` listener, the hidden div shows for a split second and then disappears like the event was fired again but away from the GeoJSON building. I also have a `'click'` listener -- `osmApplication.osmb.on('click', function(e) {...}` that runs `osmApplication.onClick` but the revealed div is stable. 

You can take a look at our development site here to get a sense of what I'm talking about [here](https://visualizations.dnainfo.com:80/skyline/nyc/browse/151/?lat=40.714639&lon=-73.988479&zoom=16.0&tilt=45.0&rotation=0.0).

Thank you!

**Comment by kekscom** [comment]
Hi!
I've checked it on Desktop and iPhone and both looking fine for me.
Besides locating the potential issue, you could work around undesired events by just setting a flag on first call and by respecting it, dropping the first onClick().
I'd also recommend the 'pointerdown' event that normalizes between touch and mouse.
