### ISSUE TITLE
Switched to Mapbox GL JS with OpenMapTiles after struggling to get examples working

### ISSUE THREAD

**Issue by wuzhou-zhang** [OSMBuildings/OSMBuildings#128]
Thanks guys for the efforts! 

I initially really wanted to use OSMBuildings, but it is super hard to get the examples working. There are all kinds of wired errors in console. A better documentation will be much appreciated.

For instance, if one opens https://osmbuildings.github.io/OSMBuildings/tutorial-Adding%20a%203D%20model.html, the console will show:

[Error] Did not parse stylesheet at 'https://raw.githubusercontent.com/OSMBuildings/OSMBuildings/master/dist/OSMBuildings/OSMBuildings.css' because non CSS MIME types are not allowed in strict mode.
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (skydome.jpg, line 0)
[Error] Cross-origin image load denied by Cross-Origin Resource Sharing policy.
[Error] TypeError: undefined is not an object (evaluating '$.parse(a).toArray')

**Comment by kekscom** [comment]
Acknowledged see your point. It's hard to keep all things running at once.
Though we would prefer contribution, I think your'e in good hands with MapboxGL + OMT.
