### ISSUE TITLE
how to remove sky

### ISSUE THREAD

**Issue by Tokkiu** [OSMBuildings/OSMBuildings#129]
hi~
I'm using the OSMBuildings for my school work about map&Visualization. :-P
Your project is so awesome!
But i faced a problem now.
I found when the map's property **zoom** >= **16**,the **sky** layer will show up automatically.
I want to **remove** the sky layer so that the map left **only**.
I search and read all the docs onsite but found nothing.
So can u help me to solve this ? :-)

**Comment by kekscom** [comment]
Hi,

I'm very glad you like OSM Buildings!

I can just assume you've meant zoom <= 16. Then we show a sky in order not to load an infinite amount of buildings.
This can't be turned off. You might limit zoom and tilt though.

Regards,
Jan

**Comment by kekscom** [comment]
Hi,

For OSM Buildings 2.5D it's the same reason. If you zoom out too far, your loading a massive amount of tiles.
And still objects wouldn't look that good anymore. You may change the limit in source code and try.

Regards,
Jan

**Comment by Tokkiu** [comment]
All right.
Thanks!
U help me a lot.
