### ISSUE TITLE
 Do not draw multipoligons

### ISSUE THREAD

**Issue by SubterrinaCB** [OSMBuildings/OSMBuildings#130]
For example: Red Square Moscow.

All buildings of Moscow Kremlin are multipoligons in OSM

https://osmbuildings.org/?lat=55.75296&lon=37.61912&zoom=18&rotation=-166&tilt=45

![image](https://cloud.githubusercontent.com/assets/27811861/25231481/ab47be28-25e0-11e7-9d13-d58745da2b5a.png)

**Comment by kekscom** [comment]
It is collections of open LineStrings. While it might be possible to form polygons and buildings out of that, the effort is far beyond our scope.

**Comment by kekscom** [comment]
But.. scope changed. This should be much better now.

**Comment by SubterrinaCB** [comment]
Better... but
http://osmbuildings.org/?lat=55.75117&lon=37.61691&zoom=17.2&rotation=0&tilt=30  




>Вторник,  8 августа 2017, 17:27 +03:00 от Jan Marsch <notifications@github.com>:
>
>But.. scope changed. This should be much better now.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Денис Р
7077740@bk.ru

**Comment by kekscom** [comment]
Of course that was to be expected :-)
LineStrings and thus floating objects are solved.
Remaining issues will be taken care of later on.

**Comment by kekscom** [comment]
There are a lot of fixes in place now. Please check again.
