### ISSUE TITLE
Egyptian pyramids in Moscow

### ISSUE THREAD

**Issue by SubterrinaCB** [OSMBuildings/OSMBuildings#131]
Incorrectly
https://osmbuildings.org/?lat=55.76334&lon=37.62141&zoom=17.8&rotation=-214&tilt=45

This Incorrectly buildins are multipoligons. 
![image](https://cloud.githubusercontent.com/assets/27811861/25231446/8fdf0bb4-25e0-11e7-87d7-381cece7b6c7.png)

**Comment by kekscom** [comment]
I'm adding these specific examples:
http://www.openstreetmap.org/way/52475409
http://osmbuildings.org/?lat=55.76366&lon=37.62446&zoom=17.4&rotation=0&tilt=30

Interesting point is that none of the buildings I've checked has a critical roof:shape value.
I'll check for that.

**Comment by kekscom** [comment]
Roofs in fact had been tagged with `roof:shape=pyramid` which is nonsense.
I've adjusted quite a few buildings to use `hipped` instead.
Please check again.
