### ISSUE TITLE
how to remove the obj

### ISSUE THREAD

**Issue by hualunchang** [OSMBuildings/OSMBuildings#132]
i had added a obj to the map,and i want to remove the obj from the map,i use the remove() function but it seems not to work
//*******************************************8
osmb.addOBJ(
    './chezhan.obj',
    { latitude:23.12951, longitude:113.31427},
    {scale : 1,color : 'red',id : "123"}
    );

osmb.getTarget(23.12951,113.31427,null).remove();

//*****************************

**Comment by kekscom** [comment]
Just do:

var myObj = osm.addOBJ(...);
...
myObj.destroy();
