### ISSUE TITLE
Roof shape rendered wrong

### ISSUE THREAD

**Issue by scit2010** [OSMBuildings/OSMBuildings#133]
Half-hipped roofs are rendered as gabled roofs. This issue is similar to that "Pyramids in Moscow" issue.
For an example see: 
https://www.openstreetmap.org/way/129750397
http://osmbuildings.org/?lat=54.43641&lon=11.20463&zoom=18.8&rotation=-14&tilt=45

For the roof shape types see:
https://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Roof

**Comment by kekscom** [comment]
Half hipped roofs are not supported yet.
Gabled roofs are just a simplified representation for that.
