### ISSUE TITLE
How to add a google map layer based on original OSMBuilding map

### ISSUE THREAD

**Issue by TomAditazz** [OSMBuildings/OSMBuildings#134]
In a project I need to add 3D buildings from .obj file to osmb map and I've done that part. But the problem is I can't add a google map layer on it. 
I was able to add both google map layer and osmbuilding layer on ol3 canvas(OSMBuilding-ol3.js). But in that way, the function osmb.addOBJ() wont work. Is there a way to show 3D buildings comes from .obj file and google satellite map in the same canvas?
Here's the code I'm using right now.
To create a osmb canvas:
var osmb = new OSMBuildings({
		    minZoom: 14,
		    maxZoom: 22,
		    position: { latitude:lat, longitude:lon },
		    zoom: zoom,
		    state: true,
		    effects: ['shadows'],
		    attribution: '© 3D <a href="https://osmbuildings.org/copyright/">OSM Buildings</a>'
		  }).appendTo('map');
osmb.addMapTiles(
		    'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
		    {
		      attribution: '© Data <a href="https://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="https://mapbox.com/">Mapbox</a>'
		    }
		  );
To add a 3D building from .obj file:
osmb.addOBJ(model_url,{ longitude:lon, latitude:lat },{scale : scale, id : id, color: color, rotation: rot});

Thanks!

**Comment by kekscom** [comment]
I don't see a simple solution here but if you're flexible about the source, 
Mapbox satellite tiles should work pretty well.

**Comment by TomAditazz** [comment]
I'll check that out, thanks!

**Comment by TomAditazz** [comment]
I use osmb.addMapTile() with a google map satellite tile as the base map. But one problem is if I want to switch the base map, I could only add one more map tile on the canvas. Is there a way to remove a map tile from the canvas?

**Comment by kekscom** [comment]
Try this:
var tiles = addMapTiles(...);
...
tiles.destroy();
