### ISSUE TITLE
Domed roofs now spread over entire building?

### ISSUE THREAD

**Issue by Ynhockey** [OSMBuildings/OSMBuildings#135]
This is a weird issue that popped up recently when no code was changed, so it might not be a code issue, but for the life of me I can't figure out how else it could have appeared (started about 1 month ago).

When there is a domed roof in the middle of a building, the renderer now enlarges it to the entire building. Example:

https://osmbuildings.org/?lat=32.09112&lon=34.88989&zoom=18&rotation=0&tilt=30

**Comment by Ynhockey** [comment]
Thanks, I noticed that this has been solved a couple of weeks ago on
osmbuildings.org .

However, on GitHub I see no changes in the project for 6 months. Is this
normal? Maybe I'm looking at the wrong repository?

Thanks again,
—Yan.

**Comment by kekscom** [comment]
You are in the right repository. The solution was only related to data.
