### ISSUE TITLE
asking for help

### ISSUE THREAD

**Issue by 349989153** [OSMBuildings/OSMBuildings#136]
I'm not reporting a bug, just looking for some help.
The problem I was running into have been post on stackoverflow, please check this:https://stackoverflow.com/questions/44448683/remove-gradient-effect-from-osm-building

I've spent a lot of time on google but can't find the solution.Please help and thank in advance.

**Comment by 349989153** [comment]
forgot to mention that I'am using the latest release version of OSMBuildings 3D

**Comment by kekscom** [comment]
This is deeply baked in by intention. It gives OSM Buildings a specific look and is in variants used on other renderers too.
The only way is to hack GL shaders for buildings.

**Comment by 349989153** [comment]
@kekscom Thanks for your time!

I will take the advice and try to dig deep into the source code.

This issue and the question on SO will be closed.
