### ISSUE TITLE
Http code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by MarnixBouhuis** [OSMBuildings/OSMBuildings#137]
I'm building a map application and after some time the map stops showing 3D data.
The console spams the following:

`OSMBuildings.debug.js:4647 GET https://a.data.osmbuildings.org/0.2/anonymous/tile/15/17612/10748.json 429 (Too Many Requests)`
(The url is different for each request made.)

After a page refresh nothing loads. 

I'm running the index.html of the latest release zip.

**Comment by kekscom** [comment]
Hi, Console says clearly you are issuing too many requests.
This is a lot more relaxed when running OSM Buildings from a web server.
