### ISSUE TITLE
Set default height for building=garage to 2m

### ISSUE THREAD

**Issue by pwithnall** [OSMBuildings/OSMBuildings#138]
It’s not really correct to tag `building=garage` with `building:levels`, since a garage doesn’t really have any levels. However, if untagged, the default rendering of garages makes them as tall as (or taller than) the surrounding 1-storey or 2-storey houses.

For example:
http://osmbuildings.org/?lat=54.29526&lon=-2.73407&zoom=19.6&rotation=0&tilt=30

Would it make sense to set the default height for rendering `building=garage` to be 2m or similar?

**Comment by wojdyr** [comment]
the same with building=shed, one level would be a reasonable default height

**Comment by kekscom** [comment]
This is still valid for us but will be solved on server side entirely.

**Comment by natrius** [comment]
Why is this closed when it is not resolved? I mean, it forces me to tag the garage with a level and thats maybe not that bad, but still. 
When its a garage or a shed the default-rendering should be building:levels=1 if there are no levels. And if a roof is present, roof:levels=1 as well. Right now its funny that the garages are that tall :)
