### ISSUE TITLE
coordinates of the objects

### ISSUE THREAD

**Issue by JPedroMG** [OSMBuildings/OSMBuildings#140]
hi @kekscom, @rbuch703, @dkniffin  , i'm beginner in this topic. i have some troubles to get the correct coordinate from a geojson polygon.

When i run my code in a window without elements, runs perfect. But my page use a couple of filters to reload the map with a ajax petition.

So when i display the filters, the "div" and the "canvas" which contains the map, they move a little down, so that affect the coordinates. So when i move the mouse above a geojson the function "map.on('pointermove', function(e)" doesn't affect the geojson beacause the coordinates still are in the same position

my question is, how i calculate this new coordinates? which function i have to run to recalculate this new coordinates?

`var valores =tRespuesta;

                var map = new GLMap('map', {
                    position: { latitude:19.067080, longitude:-104.291410},
                    zoom: 16,
                    minZoom: 12,
                    maxZoom: 22,
                    state: false // stores map position/rotation in url
                });

                var osmb = new OSMBuildings({
                    baseURL: './OSMBuildings',
                    zoom: 20,
                    minZoom: 15,
                    maxZoom: 22,
                    attribution: '© 3D <a href="https://osmbuildings.org/copyright/">OSM Buildings</a>'
                }).addTo(map);

                osmb.addMapTiles(
                    'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
                    {
                        attribution: '© Data <a href="https://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="https://mapbox.com">MapBox</a>'
                    }
                );

                for (var i =0; valores.datos.length>i; i++) {
                    var bloque = valores.datos[i]

                    //Bloques//
                    var geojson = {
                        type: 'FeatureCollection',
                        features: [{
                            type: 'Feature',
                            properties: {
                                color: '#e8dfd8',
                                roofColor: '#e8dfd8',
                                height: 0.1,
                                minHeight: 0,
                            },
                            geometry: {
                                type: 'Polygon',
                                coordinates: [
                                    [
                                        [bloque.tLongitudA, bloque.tLatitudA], 
                                        [bloque.tLongitudB, bloque.tLatitudB], 
                                        [bloque.tLongitudC, bloque.tLatitudC], 
                                        [bloque.tLongitudD, bloque.tLatitudD], 
                                        [bloque.tLongitudA, bloque.tLatitudA]  
                                    ],
                                ]
                            }
                        }]
                    }; 
                    var obj = osmb.addGeoJSON(geojson);

                    arrayObjetos.push(obj)
                    
                    //Bloques//

                    for (var x = 0; bloque.Posiciones.length > x; x++) {
                        var posicion= bloque.Posiciones[x];
                        var colorHexa = '#'+Math.floor(Math.random()*16777215).toString(16);

                        var coordenada1={long:posicion.tLongitud, lat:posicion.tLatitud};
                        var punto2=NuevoPunto(coordenada1, posicion.BearingA, (posicion.TEUs==2 ? 12.2 : 6.06));
                        coordenada2={long:punto2.long, lat:punto2.lat};
                        var punto3=NuevoPunto(coordenada2, posicion.BearingB, 2.43);
                        var punto4=NuevoPunto(coordenada1, posicion.BearingB, 2.43)

                        //Contenedores//
                        var geojson = {
                            type: 'FeatureCollection',
                            features: [{
                                type: 'Feature',
                                properties: {
                                    color: colorHexa,
                                    roofColor: colorHexa,
                                    height: 1,
                                    minHeight: 0,
                                    id:posicion.tCodPosicion,
                                    shadows:true
                                },
                                geometry: {
                                    type: 'Polygon',
                                    coordinates: [
                                        [
                                            [posicion.tLongitud, posicion.tLatitud], 
                                            [punto2.long, punto2.lat],
                                            [punto3.long, punto3.lat],
                                            [punto4.long, punto4.lat],
                                            [posicion.tLongitud, posicion.tLatitud]
                                        ],
                                    ]
                                }
                            }]
                        };
                        var obj= osmb.addGeoJSON(geojson);
                        obj.elevation= posicion.Estiba-1;
                        //Contenedores//
                        arrayObjetos.push(obj)
                    }
                }

                map.on('pointermove', function(e) {
                    var id = osmb.getTarget(e.x, e.y);
                    if(id){
                        console.log(e);
                        console.log(id);
                    }
                    if (id) {
                        document.body.style.cursor = 'pointer';
                        osmb.highlight(id, '#f08000');

                    } else {
                        document.body.style.cursor = 'default';
                        osmb.highlight(null);
                    }
                });`

i hope you can help me with this. thank you!!!

**Comment by kekscom** [comment]
Hi! Finally here..
Can you make sure by checking e.x/e.y that coordinates are really set off?
Also your HTML would be helpful. Ideally running in Codepen.

**Comment by JPedroMG** [comment]
@kekscom i appreciate your help, yesterday i solved it putting the map in a iframe, that is no the way i want to do it, but it works.

if you check this [codepen](https://codepen.io/osmbuildings/pen/avXGJy) you made, just put a div before the map like this:

`<d iv style="height:50px">space</div>
<d iv id="map"></div>`

you will notice, your pointer are in a different position than the highlighted object.

i think is that, because when the objects are rendered the viewport extract the coordinates 0,0 (left, top.... if i'm right) i tried to assign the coordinates of the div container with this function "getBoundingClientRect", but something missing and i have a similar result.

`
I.Interaction = {
        idMapping: [null],
        viewportSize: 512,
        init: function() {
            this.shader = new m.Shader({
                vertexShader: B.interaction.vertex,
                fragmentShader: B.interaction.fragment,
                attributes: ["aPosition", "aColor"],
                uniforms: ["uModelMatrix", "uViewMatrix", "uProjMatrix", "uMatrix", "uFogRadius", "uBendRadius", "uBendDistance"]
            }), this.framebuffer = new m.Framebuffer(this.viewportSize, this.viewportSize)
        },
        getTarget: function(a, b) {
            var c = this.shader,
                d = this.framebuffer;
            let coords = document.getElementById("map").getBoundingClientRect();

                    
                    // THIS ARE THE PARAMETERS I CHANGED

            n.viewport(coords.left,coords.top, this.viewportSize, this.viewportSize), c.enable(), d.enable(), n.clearColor(0, 0, 0, 1), n.clear(n.COLOR_BUFFER_BIT | n.DEPTH_BUFFER_BIT), n.uniform1f(c.uniforms.uFogRadius, I.fogRadius), n.uniform1f(c.uniforms.uBendRadius, I.bendRadius), n.uniform1f(c.uniforms.uBendDistance, I.bendDistance);
            for (var e, f, g = E.Index.items, h = 0, i = g.length; i > h; h++) e = g[h], l.zoom < e.minZoom || l.zoom > e.maxZoom || (f = e.getMatrix()) && (n.uniformMatrix4fv(c.uniforms.uModelMatrix, !1, f.data), n.uniformMatrix4fv(c.uniforms.uViewMatrix, !1, I.viewMatrix.data), n.uniformMatrix4fv(c.uniforms.uProjMatrix, !1, I.projMatrix.data), n.uniformMatrix4fv(c.uniforms.uMatrix, !1, m.Matrix.multiply(f, I.viewProjMatrix)), e.vertexBuffer.enable(), n.vertexAttribPointer(c.attributes.aPosition, e.vertexBuffer.itemSize, n.FLOAT, !1, 0, 0), e.idColorBuffer.enable(), n.vertexAttribPointer(c.attributes.aColor, e.idColorBuffer.itemSize, n.FLOAT, !1, 0, 0), n.drawArrays(n.TRIANGLES, 0, e.vertexBuffer.numItems));
            var j = d.getData();
            c.disable(), d.disable(), n.viewport(0, 0, l.width, l.height), a = a / l.width * this.viewportSize << 0, b = b / l.height * this.viewportSize << 0;
            var k = 4 * ((this.viewportSize - b) * this.viewportSize + a),
                o = j[k] | j[k + 1] << 8 | j[k + 2] << 16;
            return this.idMapping[o]
        },
        idToColor: function(a) {
            var b = this.idMapping.indexOf(a);
            return -1 === b && (this.idMapping.push(a), b = this.idMapping.length - 1), {
                r: (255 & b) / 255,
                g: (b >> 8 & 255) / 255,
                b: (b >> 16 & 255) / 255
            }
        },
        destroy: function() {}
    }`

again, thank you for your help!

**Comment by kekscom** [comment]
Alright there should be a fix in OSM Buildings. But for now, you may use offsetLeft and offsetTop of the map container.
I've updated the [Codepen](https://codepen.io/osmbuildings/pen/avXGJy) accordingly.
Note: for that technique you need to add the offsets of all parent elements.

**Comment by JPedroMG** [comment]
understood, i appreciate your time and help

**Comment by kekscom** [comment]
Fixed!
