### ISSUE TITLE
How to run the project normally?

### ISSUE THREAD

**Issue by zhouzhou-96** [OSMBuildings/OSMBuildings#141]
I know nothing about the OSMBuilding,but I have a huge interest with it.I run the project with the steps successfully:
1、Clone the repo (git clone git@github.com:OSMBuildings/OSMBuildings.git)
2、Install dependencies with npm install
3、After making changes, you can try them out by running grunt release, which will output a dist/OSMBuildings/OSMBuildings.debug.js file that you can include like normal
But when I run the dist/index.html it isn't a 3D map but a 2D map like this:
![2017-08-15 15 25 37](https://user-images.githubusercontent.com/26320443/29306169-c7d53d6e-81ce-11e7-828a-a5d309ae9593.png)
How can I do to get the result like this:
![2017-08-15 15 26 28](https://user-images.githubusercontent.com/26320443/29306219-1028eb60-81cf-11e7-9efc-4b80a96d7e63.png)
Thank you!

**Comment by kekscom** [comment]
Please use the latest release: https://github.com/OSMBuildings/OSMBuildings/releases
