### ISSUE TITLE
Middle mouse problem

### ISSUE THREAD

**Issue by SubterrinaCB** [OSMBuildings/OSMBuildings#142]
Good afternoon! 

Why earlier had the map rotated when you pressed and held the middle mouse button (the wheel), but a few days ago it stopped doing so? Now, when you hold the middle mouse button the map can only be moved left-right-up-down, i.e. the function of pressing and holding the middle mouse button has become identical to that of the left mouse button, i.e. moving of the map.

Please tell me how to return the map rotation with the middle mouse button?

**Comment by kekscom** [comment]
Hi!
This seems to be an issue with recent updates of Google Chrome. Firefox is still working.
We are going to update the behaviour to work with right mouse button.

**Comment by SubterrinaCB** [comment]
Hi!
 Left Alt+mouse - working))

**Comment by kekscom** [comment]
Fixed!
