### ISSUE TITLE
How to remove an added geojson polygon???

### ISSUE THREAD

**Issue by DuRiver** [OSMBuildings/OSMBuildings#144]
I have added a polygon using "osmb.addGeoJson(geoJsonPolygon)". Now I want to remove it, but I can't do it.

**Comment by kekscom** [comment]
var poly = osmb.addGeoJson(geoJsonPolygon);
...
poly.destroy();

**Comment by DuRiver** [comment]
@kekscom Thank you very much for solving my problem.
