### ISSUE TITLE
Tilt at 90

### ISSUE THREAD

**Issue by Wh1teFr0st** [OSMBuildings/OSMBuildings#145]
Hi,
first of all nice work. I want to ask if it is possible to set the tilt to 90 to "stand on street and look along the buildings" instead the 45?
I`m not sure if it is engine related.

**Comment by kekscom** [comment]
Hi, In theory this is possible but it would load data almost endlessly.
It needs a limitation like limited angle or some kind of distant fog.
Or decision was for angle.

**Comment by sirjamesgray** [comment]
flexible tilt (option key + click & drag cursor) would allow for 90º viewing, as well as allowing users to adjust the perspective of the viewer instead of being constrained to always facing north.

**Comment by mryellow** [comment]
There is a hard-coded constant tilt limit which you'll have to remove.

**Comment by kekscom** [comment]
I can only ask not to remove the limit. See my comment above.
@mryellow you are advising to overload our infrastructure.
