### ISSUE TITLE
Feature Request - Three.js animations layer

### ISSUE THREAD

**Issue by nareindiren** [OSMBuildings/OSMBuildings#146]
Hi,

I am just a newbie, I am working on something that requires some basic animations over the map layer. Is it possible to add three.js animations on top of OSM Buildings?

**Comment by kekscom** [comment]
Hi, This would require advanced hacking to share 3d contexts across both systems.
I'd recommend to go with a pure three.js renderer like OSM_go:
https://wiki.openstreetmap.org/wiki/OSM_go

**Comment by nareindiren** [comment]
Hi Kekscom,
Thanks for your response, any idea on how F4 maps does it? 
F4 Map: demo.f4map.com

**Comment by kekscom** [comment]
No, F4 is closed source.
