### ISSUE TITLE
Integrated 3d animation (without external renderer)

### ISSUE THREAD

**Issue by ZenPylon** [OSMBuildings/OSMBuildings#147]
This looks like a wonderful project - I really appreciate all the work you've done!  I'm currently trying to decide whether to use Mapbox GL or OSMBuildings.  I'm wanting to build a game drawn over a 3d map, and Mapbox GL doesn't seem to support arbitrary 3d models.

I know one user had requested integration with Three.js #146 , but since sharing rendering contexts would be hacky, I was wondering how much effort would be involved in adding support for 3d animation on top of the existing .obj rendering capability in OSMBuildings.

I'd be happy to contribute, though it's been a _long_ time since I've done any OpenGL.  Any suggestions on feasibility / where to begin?

Thanks!

**Comment by kekscom** [comment]
Hi, Thank you very much for considering OSM Buildings.
Animation should be possible with all candidates, including OSM_go.

Performance might be best with Mapbox GL, effects and custom OBJ are better on OSM Buildings.
OSM_go is in between.

I'd recommend to have a look into OSM Buildings **3d context creation** and **rendering passes**.
If you feel confident with these an how to **handle the camera** - then go with it.

OSM_go is based on ThreeJS and code is free to use. But you might need to fiddle a lot to get in there.

I'd be very interested in a whole now solution based on ThreeJS or a pure game engine but lacking capacity. I'm happy to assist if this is your choice.

**Comment by ZenPylon** [comment]
Thanks for your response.  Yes, I was considering using Babylon.js for the game and adding a renderer for map data later on.  It will take a while to figure out details, but I'll likely be in touch!

**Comment by kekscom** [comment]
Hi, Getting back to this. We are evaluating BabylonJS for next major version os OSM Buildings.
If you are still interested, please let me know.

**Comment by M94antony** [comment]
Hi, I'd like to see BabylonJS integrated with the OSM Buildings. I think there is a huge potential there in terms of functionality and application. have you decided on using this for the next release?

**Comment by kekscom** [comment]
We're close to it. Looks like none of the big players will suit our needs.

**Comment by kekscom** [comment]
Many apologies this got no updates.
We have a vision where next iteration of OSM Buildings will be heading and it most likely involves Three.js.
I'm closing this because there is not much to add for a while.
