### ISSUE TITLE
Change building colors dynamically

### ISSUE THREAD

**Issue by kekscom** [OSMBuildings/OSMBuildings#148]
@Vishnupriyachirappa
> how to update colors with out destyoing a tile or json object can u help with the code

Best would be using *loadfeature* event.

~~~
osmb.on('loadfeature', function(feature) {
  // modify here
  return feature;
}
~~~

**Comment by Vishnupriyachirappa** [comment]
for the first tiome its changing color but for second time onwards its 
not changing can u give a solution pls

**Comment by kekscom** [comment]
Could you please provide your example in CodePen or anything equivalent.

**Comment by Vishnupriyachirappa** [comment]
sure Here is the example
=======================================================================================================

<!DOCTYPE html>
<html>
<head>
<title>Bars Animation</title>
<meta charset="utf-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, 
user-scalable=no">
<style>
html, body {
	margin: 0;
	padding: 0;
	width: 100%;
	height: 100%;
}

#map {
	width: 100%;
	height: 100%;
}

.control {
	position: absolute;
	left: 0;
	z-index: 1000;
}

.control.tilt {
	top: 0;
}

.control.rotation {
	top: 45px;
}

.control.zoom {
	top: 90px;
}

.control.zoom button {
	font-weight: normal;
}

.control button {
	width: 30px;
	height: 30px;
	margin: 15px 0 0 15px;
	border: 1px solid #999999;
	background: #ffffff;
	opacity: 0.6;
	border-radius: 5px;
	box-shadow: 0 0 5px #666666;
	font-weight: bold;
	text-align: center;
}

.control button:hover {
	opacity: 1;
	cursor: pointer;
}

.line3 {
	stroke: purple;
	stroke-width: 6;
	stroke-dasharray: 8, 12;
}
</style>

<link rel="stylesheet" href="popup.css">
<link rel="stylesheet" href="OSMBuildings/OSMBuildings.css">
<script type="text/javascript" 
src="OSMBuildings/OSMB_HeightUpdate_animation.js"></script>

</head>

<body>

	<div id="map"></div>

	<div class="popup" id='pop' style="">
		<span class="popuptext" id="myPopup">A Simple Popup!</span>
	</div>

	<div class="control tilt">
		<button class="dec">&#8601;</button>
		<button class="inc">&#8599;</button>
	</div>

	<div class="control rotation">
		<button class="inc">&#8630;</button>
		<button class="dec">&#8631;</button>
	</div>

	<div class="control zoom">
		<button class="dec">-</button>
		<button class="inc">+</button>
	</div>


	<script>
var fEle=null;
var oVal=500;
var nVal;
var  arr;

window.requestAnimFrame = ( function() {

     return  window.requestAnimationFrame ||
             window.webkitRequestAnimationFrame ||
             window.mozRequestAnimationFrame ||
             window.oRequestAnimationFrame ||
             window.msRequestAnimationFrame ||

     // if none of the above, use non-native timeout method
     function(callback) {
       window.setTimeout(callback, 1000 / 60);
     };

   }) ();

   var osmb = new OSMBuildings({
     baseURL: './OSMBuildings',
     zoom: 15,
     //minZoom: 9,
    // maxZoom: 19,
	tilt:30,
     position: { latitude:17.416433, longitude:78.431836},
     state: true, // stores map position/rotation in url
     effects: ['shadows'],
	showBackfaces:false,
     attribution: '© 3D <a href="https://osmbuildings.org/copyright/">OSM 
Buildings</a>'
   }).appendTo('map');

//https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png

//tiles/{z}/{x}/{y}.png
   osmb.addMapTiles(
     
'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
     {
       attribution: '© Data <a 
href="https://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a 
href="https://mapbox.com/">Mapbox</a>'
     }
   );
   osmb.on('loadfeature', function(feature) {
	  console.log("feature:",feature);
	  var height= parseInt(feature.detail.properties.height);
	  var color=null;
	 if(height<300){
		 color="red";
	 }
	 else{
		 color="green";
	 }
	  feature.detail.properties.color=color;

	  return feature;
	})

  osmb.addGeoJSONTiles('geojson/OSMB_HeightUpdate.json');
  //osmb.addGeoJSON('geojson/heightUpdate.json');

  setInterval(function(){
	 readTextFile('sampleData.jsp');
  }, 3000);


    /*  window.requestAnimFrame(function() {
	  readTextFile('sampleData.jsp');
   });  */

  function readTextFile(url) {
	// setTimeout(function() {
		 var rawFile = new XMLHttpRequest();
			rawFile.overrideMimeType("application/json");
			rawFile.open("GET", url, true);
			rawFile.onreadystatechange = function() {
				if (rawFile.readyState === 4 && rawFile.status == "200") {
					getData(rawFile.responseText);
				}
			}
			rawFile.send(null);
			  /* window.requestAnimFrame(function() {
				  readTextFile('sampleData.jsp');
			  });  */
	// },1500.0);
}

	function getData(text){
		arr = JSON.parse(text);
		osmb.setValue(arr);
	}

   
//***************************************************************************

   osmb.on('pointermove', function(e) {
     osmb.getTarget(e.detail.x, e.detail.y, function(id) {
       if (id) {
         document.body.style.cursor = 'pointer';
         osmb.highlight(id, 'blue');
		tooltip(e);
       } else {
         document.body.style.cursor = 'default';
         osmb.highlight(null);
       }
     });
   });

   function tooltip(e){
	      var pop = document.getElementById('pop');
	      var popup = document.getElementById('myPopup');
	       pop.style.left = e.detail.x+"px";
		   pop.style.top = e.detail.y+"px";;
		   popup.innerHTML= e.timeStamp;
            popup.classList.toggle('show');
   }

//osmb.addOBJ('airboat.obj', { latitude: 17.416433, longitude: 78.431836 
}, { id: "my_object_1", color: 'red'});
var geojson = {
   type: 'FeatureCollection',
   features: [{
     type: 'Feature',
     properties: {
       color: 'red',
       roofColor: 'blue',
       height: 250,
       minHeight: 0,
       id:"r001"
     },
     geometry: {
       type: 'Polygon',
       coordinates: [
         [
           [17.41000, 78.44000],
           [17.41010, 78.43000],
           [17.41010, 78.43010],
           [17.41000, 78.43010],
           [17.41000, 78.44000]
         ]
       ]
     }
   }]
};
//osmb.addGeoJSON(geojson);

   
//***************************************************************************

   var controlButtons = document.querySelectorAll('.control button');

   for (var i = 0, il = controlButtons.length; i < il; i++) {
     controlButtons[i].addEventListener('click', function(e) {
       var button = this;
       var parentClassList = button.parentNode.classList;
       var direction = button.classList.contains('inc') ? 1 : -1;
       var increment;
       var property;

       if (parentClassList.contains('tilt')) {
         property = 'Tilt';
         increment = direction*10;
       }
       if (parentClassList.contains('rotation')) {
         property = 'Rotation';
         increment = direction*10;
       }
       if (parentClassList.contains('zoom')) {
         property = 'Zoom';
         increment = direction*1;
       }
       if (property) {
         osmb['set'+ property](osmb['get'+ property]()+increment);
       }


     });
   }

</script>
</body>
</html>
========================================================================
i am calling loadfeatures

function repeatedCode(thisObj) {

             	  heights = findCurrentHeights();
             	  if(ia.dataGrid) ia.dataGrid.destroy();
             	  //Ha.Index.destroy();
             	  thisObj.items = [];
             	  isNext = false;

             	  e = [];
           		  d.vertices=[];
             	  var k, l, m, n, o, p;
             	  thisObj.idMapping=["PS1","PS2","PS3","PS4","PS5","PS6"]
             	  for(var index=0; index<a.features.length; index++) {

             		  a.features[index].properties.height = heights[index];
             		color="#"+((1<<24)*Math.random()|0).toString(16);

             		 var b=a;
             		  k = b.features[index];

			 			 ia.emit("loadfeature", k);
			 			 l = k.properties;
			 			 m = thisObj.forcedId || l.relationId || k.id || l.id;
			 			 n = d.vertices.length;
			 			 ga(d, k, f, thisObj.forcedColor);
			 			 o = (d.vertices.length - n) / 3;console
			 			p = Ja.Picking.idToColor(m);
		         p=[Math.random(),0,0]
			 	   for (var r = 0; r < o; r++){
		        	  [].push.apply(e, p);
		           }

		           thisObj.items.push({
	        		   	id: m,
                         vertexCount: o,
                         height: l.height,
                         data: l.data
	               });
	              	  thisObj.vertexBuffer = new ba.Buffer(3, new 
Float32Array(d.vertices));
	              	  thisObj.normalBuffer = new ba.Buffer(3, new 
Float32Array(d.normals));
	              	  thisObj.colorBuffer = new ba.Buffer(3, new 
Float32Array(d.colors));
	              	  thisObj.texCoordBuffer = new ba.Buffer(2, new 
Float32Array(d.texCoords));
	              	  thisObj.idBuffer = new ba.Buffer(3, new 
Float32Array(e));
	              	  thisObj._initItemBuffers();
	              	  Ga.apply(thisObj);
	              	  Ha.Index.add(thisObj);
	              	  thisObj.isReady = !0;
	              	  void ma.setIdle();
              		}
             	  if(count != 0) j();
             	  count++;
               }



================internal code is modifdied to repeted code

**Comment by kekscom** [comment]
First of all, this is not a running CodePen or similar example.
Please do not expect me to set this up and debug for you.

Second, I've noticed *osmb.setValue(arr)* which is unknown to me.

Last: if you do modifications in OSM Buildings code, please use the non-minified debug version from a release or create a fork and work in source code. This makes review a lot easier.

I hope this doesn't sound impolite, but there are a lot of requests to answer day by day and this is not commercial software support.

**Comment by Vishnupriyachirappa** [comment]
sorry for the inconvenience here i am attaching the code file.if u don't 
mine can u tell the way please while bar is increasing color should be 
change.
