### ISSUE TITLE
Reversed roofs, misaligned roof lines and non-proportional dome scaling

### ISSUE THREAD

**Issue by Swyter** [OSMBuildings/OSMBuildings#149]
Compare this:
![imagen](https://user-images.githubusercontent.com/690187/33515644-5c059c4e-d766-11e7-9510-be64ad283185.png)
https://osmbuildings.org/?lat=42.00182&lon=-5.68047&zoom=20&tilt=26&rotation=-93

with this:
![imagen](https://user-images.githubusercontent.com/690187/33515647-7d6a2580-d766-11e7-934e-e3aadc889aea.png)
http://demo.f4map.com/#lat=42.00182&lon=-5.68047&zoom=20&camera.theta=39.843&camera.phi=95.684

There are some other handy test cases nearby. But, basically, I can see that the rooftop inclination is reversed, that the domes are scaled in a single axis and a bunch of other issues.

Anyway, cool little project you have here.

**Comment by kekscom** [comment]
Fixed in latest version.
