### ISSUE TITLE
Color regression in 3.2.7?

### ISSUE THREAD

**Issue by Ynhockey** [OSMBuildings/OSMBuildings#150]
It looks like in the new version there are two issues with colors:

1. Glass now defaults to white
2. Certain color words, such as peachpuff, that previously worked, also now default to white

Example where these issues can be seen:
https://osmbuildings.org/?lat=32.08341&lon=34.80371&zoom=16.6&rotation=0&tilt=28

I think the final commit is one of the ones responsible:
https://github.com/OSMBuildings/OSMBuildings/commit/6018266452bfec593b0e1fa8ecaf8c18d55d6170

**Comment by kekscom** [comment]
I've reduced color changes introduced in last version. Should be a lot better.
