### ISSUE TITLE
Certain buildings not appearing properly since last release

### ISSUE THREAD

**Issue by Ynhockey** [OSMBuildings/OSMBuildings#152]
I'm not sure if this is a software or a data problem, but certain buildings have stopped appearing altogether, or now appear incorrectly, since the last release. Examples:

* Way 32635200 (Azrieli Mall, Tel Aviv, Israel) does not show up
* Way 509823725 (part of the Azrieli Sarona Tower in Tel Aviv, Israel), which has a min_height of 231.3, actually goes all the way down.

The view: https://osmbuildings.org/?lat=32.07388&lon=34.79139&zoom=17.2&rotation=0&tilt=28

Thanks in advance!

**Comment by kekscom** [comment]
Thank you for reporting. Some data seems to be corrupted.
Our next update will have it looking like this:
<img width="1091" alt="screenshot 2018-02-21 15 37 48" src="https://user-images.githubusercontent.com/1887727/36485821-5b1779a0-171d-11e8-9055-18de839d5961.png">
