### ISSUE TITLE
Cant do any changes to 3d object imported to OSM Buildings

### ISSUE THREAD

**Issue by M94antony** [OSMBuildings/OSMBuildings#153]
Hi
I can't seem to be able to make changes to the object created via  this method
https://osmbuildings.github.io/OSMBuildings/tutorial-Adding%20a%203D%20model.html

The canvas doesn't update the color.

@ Edit
Destroying works but still seems a little crude to destroy a object and recreate it to make a simple color change

my code 
```
_.forEach(data.objects, function(signal){
				var temp = _.find(objects_list, function(item){		return item.id === signal.id; });
				if(temp){
					// temp.obj.forcedColor = getRGB(signal.status); // this doesn't work neither does highlight function
					objects_list = _.remove(objects_list, function(currentObject) {
					    return currentObject.id !== temp.id;
					});

					temp.obj.destroy();
					objects_list.push({
						id: signal.id,
						obj: addObject(osmb, {
							latitude: signal.latitude,
							longitude: signal.longitude,
							id: signal.id,
							status: signal.status
						})
					});
				}
				else{
					objects_list.push({
						id: signal.id,
						obj: addObject(osmb, {
							latitude: signal.latitude,
							longitude: signal.longitude,
							id: signal.id,
							status: signal.status
						})
					});
				}
			});
```
```
function addObject(osmb, data){
		return osmb.addOBJ('assets/sphere.obj', { latitude: data.latitude, longitude: data.longitude }, { id: data.id, color: data.status});
}
```
Any ideas?

**Comment by kekscom** [comment]
So far implementation is not intended to handle any color / shape changes.
We might solve it differently in future.

**Comment by M94antony** [comment]
Thank you for your time and reply :) 
I am planning on using 3D maps and visualizations within them, which would mean manipulating a lot of objects and interactivity and animations, is OSMBuildings capable of these functions?, any specific limitations? any other lib suggestions? or should I implement using threejs with using Overpass API for extracting the relevant features - which could be reinventing the wheel?.
Thanks

**Comment by kekscom** [comment]
Start from the characteristics of your application. Is it more map like, then things would be rather static. This applies to a small set of frameworks, including OSM Buildings.
If it is game like and highly interactive, better choose something different. A bigger framework like ThreeJS or Babylon could do.
Looks like there will be quite some work to do either way.
As soon as you have limited map area and not too much zoom, you could go for game like.
You could still use our data.

**Comment by M94antony** [comment]
Thank you for your input, my application would be the latter where interactivity is highly required -> game-like. I will look at Babylon. Threejs (will very much need to use OSMBuilding data) and try a viable find. Thanks 👍
