### ISSUE TITLE
Building colors renders not the same on different PCs

### ISSUE THREAD

**Issue by maurotdo** [OSMBuildings/OSMBuildings#156]
Hi, we're having a weird issue in which different PCs, but with the same OS version / browser version, the rendering of the building differs wildly:

E.g. this is a render from osmbuildings.org on mac OS sierra 10.12.6 with latest Chrome:

![immagine](https://user-images.githubusercontent.com/3099291/41668537-daa3ba68-74af-11e8-8fbd-9e565d9a53fe.png)

Ths is the same render on another mac OS sierra 10.12.6 with same latest Chrome:

![immagine](https://user-images.githubusercontent.com/3099291/41668584-f1a38e28-74af-11e8-85ff-fae9c9f8a0ff.png)

The same render pasted above is shown on Windows, yet other windows machine show the first version. We have not found an evidence or correlation based on browser or OS versions, it just seems random. 

Is there something i'm missing, is this a known issue, or something else?

Thanks, 
Mauro

**Comment by kekscom** [comment]
Hi, Can you make sure screen shots are taken at the same time?
Our shading is day/time dependent.

Also if graphics hardware is different, then capabilities will be as well.

Things will get interesting if everything is comparable.

Regards,
Jan

Am 20.06.2018 um 17:34 schrieb Mauro Maggi <notifications@github.com>:

Hi, we're having a weird issue in which different PCs, but with the same OS version / browser version, the rendering of the building differs wildly:

E.g. this is a render from osmbuildings.org on mac OS sierra 10.12.6 with latest Chrome:



Ths is the same render on another mac OS sierra 10.12.6 with same latest Chrome:



The same render pasted above is shown on Windows, yet other windows machine show the first version. We have not found an evidence or correlation based on browser or OS versions, it just seems random.

Is there something i'm missing, is this a known issue, or something else?

Thanks,
Mauro

**Comment by maurotdo** [comment]
Hi, yes the screenshot were taken at the same time (look at the shadows), the first on my macbook pro 2017, the latter on a 2015 macbook pro with same OS version (10.12.6 ) and same Chrome version (67.0.3396.87). IT seems like the shader implementation applied to the "default color" for buildings differs on the two systems

**Comment by kekscom** [comment]
It is probably worth checking console for messages.
However, graphics hardware is not identical. Likely render precision, capabilities and drivers are different.
