### ISSUE TITLE
Loading .OBJ causing strange render issue

### ISSUE THREAD

**Issue by Girby** [OSMBuildings/OSMBuildings#157]
I am new to this kind of development and have been trying to import a 3D object (.obj) into the map. I currently have a produced .obj file, but loading the object leaves with me with a very strange render. (the actual object does not look like this when viewed in blender).

![renderissue](https://user-images.githubusercontent.com/39339216/41672105-000e79fe-74b1-11e8-8fba-3cf4809d9488.png)

As you can see this is not right. At first glance I assumed that there are too many polygons? Downloading any free .obj file online mimics this issue, however loading in the sample .obj found on - https://osmbuildings.org/ works flawlessly, so does a .osm exported as .obj.

Any help would be much appreciated,

Thanks.

**Comment by kekscom** [comment]
Hi,
Please make sure models are triangulated.
You could use blender to enforce it upon saving.

Regards,
Jan

Am 20.06.2018 um 18:44 schrieb Girby <notifications@github.com>:

I am new to this kind of development and have been trying to import a 3D object (.obj) into the map. I currently have a produced .obj file, but loading the object leaves with me with a very strange render. (the actual object does not look like this when viewed in blender).



As you can see this is not right. At first glance I assumed that there are too many polygons? Downloading any free .obj file online mimics this issue, however loading in the sample .obj found on - https://osmbuildings.org/ works flawlessly, so does a .osm exported as .obj.

Any help would be much appreciated,

Thanks.

**Comment by Girby** [comment]
Brilliant! Thank you very much, loading objects is working perfectly for me now. Is it possible to load textures onto a object? I have the .mtl file and some pngs but no textures are being loaded.

Thanks.

**Comment by Girby** [comment]
Is there a plan in the future for texture support?

**Comment by kekscom** [comment]
There are lots of plans. Realistically not in near future.
