### ISSUE TITLE
remove geojson object and z-ordering of layers

### ISSUE THREAD

**Issue by primvla** [OSMBuildings/OSMBuildings#158]
Hello!

Is there a method to remove an object added with addGeoJSON to the 3D map (by some id or something)?

Question number 2: is there a possibility to render a layer (again, in 3D map) of e.g.: parcel / property polygons to show on top of the 3d buildings layer, I mean, top like z-sorted above the geometry?

cheers!

**Comment by kekscom** [comment]
Hi, you can use var my `obj = addGeoJSON(..)` and then `obj.destroy()`

For 2: you may add more geometry that will be sorted in properly.
To make it float, use property `minHeight` per feature.

**Comment by primvla** [comment]
Thanks. With z-ordering I meant not above in 3d but above in rendering. To draw something on the floor and still be visible even though the buildings layer is on the top. Or is this possible only in classic?

**Comment by kekscom** [comment]
It seems you are destroying the whole OSMBuildings viewer rather than just an object/layer.
If the issue remains, please provide a running example of your project.

**Comment by illsio** [comment]
@kekscom ok sorry - that is also what you suggested in the first place.
my fixed code would be:
```
  createBuildingsLayer(jsonData) {
    if (this.gJson) {
      this.gJson.destroy();
    }
    
    if (!this.osmb) {
      this.osmb = new OSMBuildings({
        baseURL: './OSMBuildings',
        minZoom: 15,
        maxZoom: 22
      }).addTo(this.glMap);

      this.osmb.addMapTiles(
        'http://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png'
      );
    }

    if (jsonData) {
      this.gJson = this.osmb.addGeoJSON(jsonData);
    }
  }
```
