### ISSUE TITLE
 Loading problem of local obj 

### ISSUE THREAD

**Issue by ailmee** [OSMBuildings/OSMBuildings#160]
Loading local obj error, URL must be http/https, reporting cross domain issues 。
    map.addOBJ("geoJson/male.obj",
        { latitude:52.524133, longitude:13.407434 },
        { id:'Fernsehturm', scale:2, color:'#ff0000', altitude:0, rotation:51 }
    );
 Run by WebStorm 。

**Comment by kekscom** [comment]
Please run/use a web server in order to use OSM Buildings.

**Comment by kekscom** [comment]
As it pops up in various ways, if you need to create an suitable url dynamically:
~~~js
osmb.addOBJ(`${location.protocol}//${location.hostname}/${location.pathname}/Fernsehturm.obj`, { latitude:52.52000, longitude:13.41000 }, { id:'Fernsehturm', scale:1, color:'#ff0000', altitude:0, rotation:51 });
~~~

**Comment by mryellow** [comment]
You need to stop repeating this "solution" over and over and instead fix the `Request.load(url)` method to support valid URLs.
