### ISSUE TITLE
Color styling options don't work

### ISSUE THREAD

**Issue by pavelsl** [OSMBuildings/OSMBuildings#164]
Changing `options.backgroundColor` or `options.style.color` doesn't change anything. Is it a bug? 
Or these settings overrided by any hardcoded geojson layers colors? 

Could you create an option to have transparent background?

**Comment by BTF-Sang** [comment]
I also encountered this problem, set the transparency of the building when it is not initialized, I hope that there are any parameters that can be modified.

**Comment by kekscom** [comment]
Apologies for the delay.
backgroundColor is not in effect anymore. Use the - yet not documented - option fogColor instead.
It affects underlying base color AND fog color.

There is not way to achieve transparency.

**Comment by Cobertos** [comment]
Oh, I see, `.fogColor` is not deprecated anymore in the current master branch.

Still wondering on `.style.color` not working though.

**Comment by hugonbgg** [comment]
There a way to change the building color?
