### ISSUE TITLE
Could you create an option to have transparent background?            

### ISSUE THREAD

**Issue by BTF-Sang** [OSMBuildings/OSMBuildings#165]
I have a problem now.Changing `options.style.color` doesn't change anything.
         I need to initialize the color and transparency of the building when initializing the 3D map, especially transparency.
         And.....still a problem, buildings loading is very slow, I use the form of 'http://..../x/y/z.json' to load, dragging the map is also very slow, is there any solution?

**Comment by kekscom** [comment]
1. This is not an OSMB option.
2. There is no transparency available. See other issue comments.
3. Something being slow can be your data, your computer, your internet - and possibly OSM Buildings. An example would be helpful as well as your expectation of not being slow.
