### ISSUE TITLE
Problem with selecting buildings from OSMtiles

### ISSUE THREAD

**Issue by hodorogandrei** [OSMBuildings/OSMBuildings#166]
I am working on a project involving adding secondary geoJSON models alongside the OSMbuildings tiles (`https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json`).

I do this by using the `addGeoJSON` method.

When I do this, the following problem appears when attempting to select a building:
the selection of a building works as long as the respective building is in-view. As soon as we  go into another area of the map when the building is no longer in view, the selection of the respective building no longer works. The page needs to be refreshed in order for the selection to work again.

However, if we remove the secondary geoJSON models, the selection works normally.

**Comment by kekscom** [comment]
Could you provide a running example of this please? Codepen etc...

**Comment by hodorogandrei** [comment]
please see here: http://osmexample.surge.sh

**Comment by kekscom** [comment]
This seem odd. I did a separate test because it was not clear which buildings you've added.
https://codepen.io/anon/pen/REWaBO
I think this works as expected.
Perhaps you can copy / compare?
