### ISSUE TITLE
Use 3D Model Repository

### ISSUE THREAD

**Issue by jluttine** [OSMBuildings/OSMBuildings#168]
Would be great if OSM Buildings could use 3D models from 3D Model Repository [3dmr.eu](https://3dmr.eu). For instance, [Eiffel tower](https://www.openstreetmap.org/way/5013364) has `3dmr=4` tag but it's not rendered with the 3dmr model. Would this make sense?

**Comment by kekscom** [comment]
Yes this would be a great addition.
Closing here but he keep it on our list.

**Comment by thibaultmol** [comment]
@kekscom Guessing nothing has changed yet regarding implementing this?

(guess it's a bit of a chicken and egg problem. pretty much no tool utilizes that repository. 
And because nobody uses it, nobody feels like actually putting 3d models on there)

**Comment by kekscom** [comment]
Unfortunately no news here.

**Comment by kekscom** [comment]
Linking to #215
