### ISSUE TITLE
Render landuse=forest and natural=tree with 3D objects

### ISSUE THREAD

**Issue by jluttine** [OSMBuildings/OSMBuildings#169]
Using 3D objects for trees and tree rows tagged with `natural` and larger forest areas tagged with `landuse=forest` would be awesome. I noticed that the proprietary f4map is doing this and it looks amazing. Probably many other natural/landuse could be rendered with some 3D objects too.

**Comment by kekscom** [comment]
Another one we would love to have. We're also well aware about the visual improvement.
OTOH this would take a lot of capacity we don't currently have.

**Comment by natrius** [comment]
Could you try to get microgrants https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020 to get some help for that? Ressources i mean?
