### ISSUE TITLE
Can't move after addOBJ

### ISSUE THREAD

**Issue by 330595524** [OSMBuildings/OSMBuildings#173]
Can't move after addOBJ，
After adding the obj model, it cannot be moved；
Can't move after adding the obj model? Is Float32Array unable to modify the corresponding value?
translateTo(e, t, n) {
			return this.data[12] = e, this.data[13] = t, this.data[14] = n, this
		}

**Comment by kekscom** [comment]
Please try this:
```
let obj = osmb.addOBJ(...)
obj.longitude = x
obj.latitude = y
```

**Comment by 330595524** [comment]
Thank you for your attention，
I'm using osmbuild，API    addOBJ(),but the height of obj is not in effect   (altitude);

**Comment by 330595524** [comment]
can  you  help  me

**Comment by kekscom** [comment]
I might be able to help sooner if you could provide a running version of your project.


Am 06.08.2019 um 11:49 schrieb AM_smart <notifications@github.com>:

Thank you for your attention，
I'm using osmbuild，API addOBJ(),but the height of obj is not in effect (altitude);
