### ISSUE TITLE
 osmb.addOBJ - SyntaxError: The URI is malformed. 

### ISSUE THREAD

**Issue by mrene1** [OSMBuildings/OSMBuildings#174]
Following is the related error getting error message after osmBuildings 4 version.
SyntaxError: The URI is malformed.
The code I wrote is as follows.
osmb.addOBJ ('data/example.obj', {longitude: 1, latitude: 1}, {id: "1", scale: 5});

**Comment by kekscom** [comment]
I can't reproduce this. Also the error message doesn't seem to be related to OSMB nor to loading an obj file.
Please comment out the line and recheck.
If it helped, post the obj files and/or provide a running example to have a look at.

**Comment by mrene1** [comment]
[sample.zip](https://github.com/OSMBuildings/OSMBuildings/files/3356618/sample.zip)
the relevant examples are attached. thank

**Comment by kekscom** [comment]
Use absolute URLs to reference your file. Tested with OSM Buildings 4.0.4
Hint: if your model shows odd triangles, enable 'triangulate' upon export from your 3d software.

**Comment by kekscom** [comment]
For creating absolute URLs dynamically:
~~~js
osmb.addOBJ(`${location.protocol}//${location.hostname}/${location.pathname}/Fernsehturm.obj`, { latitude:52.52000, longitude:13.41000 }, { id:'Fernsehturm', scale:1, color:'#ff0000', altitude:0, rotation:51 });
~~~

**Comment by mryellow** [comment]
This is due to how these are passed through to `XMLHttpRequest`. There is no support for valid URIs added to these wrappers and instead they're passed straight through.

The appropriate URI construction should take place in `Request` and be abstracted away from the user at `addOBJ` and `load(url)`.

https://github.com/MomsFriendlyDevCo/OSMBuildings/issues/1

**Comment by kekscom** [comment]
I'Ve described a simple solution that allows you to modify your relative URLs as well as adding reuired absolute ones.
Raising this over and over doesn't serve anything positive.
