### ISSUE TITLE
Tween example is not smooth

### ISSUE THREAD

**Issue by ronanmcnulty** [OSMBuildings/OSMBuildings#175]
The animate tween example is not smooth. I have tried multiple implementations and versions

https://codepen.io/rmcnulty/pen/NZBxdY

**Comment by kekscom** [comment]
I don't see how this report and your code belongs to OSM Buildings.

**Comment by ronanmcnulty** [comment]
Hi @kekscom, it is a simplified version of the no longer working example in:
docs/examples/animate_tweenjs.md
