### ISSUE TITLE
Building outline and parts in case of non-existing relation

### ISSUE THREAD

**Issue by chram2** [OSMBuildings/OSMBuildings#182]
In case there is no building relation to sum up building outline and all parts, the outline is shown as 3D body.
This causes overlapping with the parts.
Would it be possible to show the outline with height of 0 (footprint only) oder e.g. max. 3 m, if the nodes of the outline belong to building parts too?
It would reduce or avoid overlap and make unnecessary to create relations for simple geometries.

**Comment by kekscom** [comment]
We follow (even accidental) intention of the mapper. If he creates a colliding polygon we show it.
Exception are relation members marked as outline. Bute even then some circumstances will keep them visible.
Other exception is a building entirely covering parts.

We don't see changes to this anytime soon.
