### ISSUE TITLE
coloring book style

### ISSUE THREAD

**Issue by MichalPP** [OSMBuildings/OSMBuildings#184]
I would like to transform a 3d model of building into a children's coloring book. 

in the style, this means just setting all the backgrounds to white and create visible black borders to all elements. but do not display the unvisible elements. so similar to skeleton model but the rear parts of the skeleton not visible.

and on export site, just set lat,lon,tilt and rotation to export into png/pdf. (maybe add some nice stuff like clouds, sun, ...)

has anyone experimented with this?

how to create automatic rewriting of the style? (so that it keeps working even after 3d building schema change)

**Comment by kekscom** [comment]
There have been experiments to render into SVG.
The whole concept lacks proper depth stacking.
Please see attachment.


[Archiv.zip](https://github.com/OSMBuildings/OSMBuildings/files/3830954/Archiv.zip)

**Comment by MichalPP** [comment]
first, just a black and white model. I will need to test this on real children (whether they will enjoy it, what size is good, if it's not too black, ...)

automatic export into SVG would be a second step. For now, just a screenshot of the website is sufficient.
