### ISSUE TITLE
Color rendering is very archaic

### ISSUE THREAD

**Issue by morray** [OSMBuildings/OSMBuildings#19]
Hi it seems that the colour rendering is only using several defined colours while other implementations interpret more precise values as hexadecimal #ccef34. See for example here: http://demo.f4map.com/

**Comment by rbuch703** [comment]
No, OSMBuildings also parses hex colors if they are present. See for example the buildings at http://osmbuildings.org/?lat=52.12549&lon=11.63380&zoom=17.4&tilt=30 , which have only hex color information in OSM and are nevertheless tinted in OSMBuildings.

But OSMBuildings prioritizes conflicting information differently that f4 and others: if the OSM data contains information on color **and** material for a building, OSMBuildings will use the material information and ignore the color information. This will make some buildings look different in OSMBuildings than they do in other renderers.

**Comment by kekscom** [comment]
Precedence could be swapped.

**Comment by morray** [comment]
Yes I think that should be done. The precendence should be (including future features)
* material + color code combination
* color code
* material
* color name

**Comment by morray** [comment]
I think this region shows nicely the difference
http://osmbuildings.org/?lat=48.161542&lon=11.5809818&zoom=17.0&tilt=30
http://demo.f4map.com/#lat=48.1615428&lon=11.5809818&zoom=18&camera.theta=58.628&camera.phi=-34.238

**Comment by kekscom** [comment]
I've changed precedence like:

1. explicit color
2. implicit color by material
3. default color

Rev: https://github.com/OSMBuildings/OSMBuildings/commit/c33427a69d16ab8bbcca5d463054ef9d6951b718
