### ISSUE TITLE
stop updating after adding geojson tiles

### ISSUE THREAD

**Issue by StevePain** [OSMBuildings/OSMBuildings#190]
Hello

i am testing the osmbuildings features 
and i am curious if there is a way to stop the updating process after the addgeojsontiles command.
I tried the osmb.remove(dataGrid); but still it keeps calling the tileserver and re-building the datagrid

thank you
Steve

**Comment by kekscom** [comment]
Hi Steve

Maybe don't add tiles at all:
~~osmb.addGeoJSONTiles('https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');~~

Or if you need them first:

`const tiles = osmb.addGeoJSONTiles('https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');`
then
`osmb.remove(tiles);`

What are your trying to achieve?

Jan
