### ISSUE TITLE
OBJ files not rendering

### ISSUE THREAD

**Issue by perniklas** [OSMBuildings/OSMBuildings#191]
Hello, I'm trying to add either one or several OBJ files using map.addOBJ(fileURL, position, options) but while the files are added and the data is "in the map", no rendering is done and the 3D models are not visible. I've checked the files themselves and they work fine in web viewers

**Comment by kekscom** [comment]
There are several flavours of OBJ. OSM Buildings supports only a subset.
Please make sure your file is triangulated. Another import/export with appropriate settings in your 3d software might help.

**Comment by perniklas** [comment]
While I have no experience in 3D modelling, I tried with multiple files including one from an earlier issue [(the man with a hat)](https://raw.githubusercontent.com/dkniffin/osm-game/master/app/assets/models/Dave.obj). There are no errors thrown, and debugging shows that addOBJ return a Feature object

**Comment by kekscom** [comment]
For triangulation I see a possible improvement but can't promise any timeline.
If you can manage to pre-triangulate, it should solve it.
If uncertain what might be wrong, please make the file available for inspection.

I'm not aware of a file size but surely at some point things will fail. How big is the file in terms of bytes, extent, triangles?
