### ISSUE TITLE
Support for all HEX colours?

### ISSUE THREAD

**Issue by natrius** [OSMBuildings/OSMBuildings#192]
Thanks for your work, i'm trying to map part of my city in 3D.

Is it planned to get support for all HEX colours ( https://en.wikipedia.org/wiki/Web_colors ) or will you just support the "official" ones like https://wiki.openstreetmap.org/wiki/Simple_3D_buildings here mentioned?

Best regards

**Comment by kekscom** [comment]
HI,
We are supporting these web safe color names: https://github.com/kekscom/Color/blob/master/src/Qolor.js#L177
and these hex / rgb(a) notations:
https://github.com/kekscom/Color/blob/master/src/Qolor.js#L22
This should cover a reasonable amount of cases.
What are you missing?

**Comment by natrius** [comment]
Oh damn. It seems that was a case of "to excited to see just some colours rendered but not all and could not wait longer". Sorry ^^°
