### ISSUE TITLE
roof:shape=round not rendered

### ISSUE THREAD

**Issue by natrius** [OSMBuildings/OSMBuildings#193]
According to your list posted in https://github.com/OSMBuildings/OSMBuildings/issues/180 round should work. 

https://www.openstreetmap.org/way/97260549 this building and the one north from it. https://osmbuildings.org/?lat=47.82850&lon=13.03868&zoom=20.0&tilt=41&rotation=11

![image](https://user-images.githubusercontent.com/7243447/75392589-a0b58c00-58ec-11ea-94ac-c986c32f13e6.png)

**Comment by kekscom** [comment]
I'm closing this in favour to #180
