### ISSUE TITLE
Some gabled roofs rendered flat

### ISSUE THREAD

**Issue by jluttine** [OSMBuildings/OSMBuildings#194]
Here's a group of buildings and most of them have gabled roofs: https://osmbuildings.org/?lat=61.50330&lon=23.78783&zoom=20.0&tilt=45&rotation=-52

However, many of those gabled roofs are rendered flat. I don't see the reason why. There's a bunch of very similar buildings that are tagged very similarly, but still the rendering differs: some gabled roofs are rendered gabled and some gabled roofs are rendered flat.

For comparison, it works fine on F4map: https://demo.f4map.com/#lat=61.5033971&lon=23.7880265&zoom=20&camera.theta=71.643&camera.phi=63.025

I don't believe this is a caching issue on browser side because I've tried many different browsers and they all show the same issue. Also, these tags have been set last summer, so they're not recent.

Any ideas what's going on?

**Comment by kekscom** [comment]
Hi, please provide specific details about what is tagged and how it differs from your expectation.
A direct link to an OSM object would be helpful (https://osm.org/way/xxxx)

We find references to commercial competitors generally annoying.

**Comment by jluttine** [comment]
Thanks for the response! And, yes, I understand that the references to commercial competitors annoy, sorry about that. OSMBuildings is an amazing project, huge thanks for your efforts on that!

Here's one of those incorrectly rendered buildings: https://www.openstreetmap.org/way/100276119

Relevant tags for the building way:

```
building=apartments
building:levels=1
roof:levels=1
roof:shape=gabled
```

I would have expected the roof to be rendered as gabled, but it was rendered flat. 

For instance, this nearby building renders just fine: https://www.openstreetmap.org/way/100276126

These two buildings have identical tags (except `addr:unit` is different). So I don't understand why they are rendered differently.

**Comment by kekscom** [comment]
Apologies if this has been impolite.
Your information now gets us forward. At least there is nothing obviously wrong tagging or imported data.
I'll have a look into the code.

**Comment by kekscom** [comment]
There is a new version in place fixing this and potentially similar issues.
https://github.com/OSMBuildings/OSMBuildings/commit/1c6d5ecf7a096a560723a239903458dfa343c35a
Issue has been caused by round ding differences, especially on almost horizontally or vertically aligned buildings.

**Comment by jluttine** [comment]
Wow, it works now! Huge thanks for your super-fast fix! :D

**Comment by kekscom** [comment]
Don't get too excited. This is not the regular response time :-)
