### ISSUE TITLE
Feature idea: Default values depending on other tags

### ISSUE THREAD

**Issue by jluttine** [OSMBuildings/OSMBuildings#195]
I was thinking that the rendering of incompletely tagged buildings could perhaps be improved by making the default values depend on some other tags (by some rules). For instance, I'm seeing a lot of tall garages because by default they are rendered quite tall compared to nearby buildings that have explicitly set levels to 1 (or 1+1). So, for `building=garage` it might be good to assume `building:levels=1` and `roof:levels=0` unless other values are explicitly given. Similarly, huts could be `building:levels=1`, `roof:levels=1` and `roof:shape=gabled`. And so on. Just some values that are quite typical or make the building look more recognizable.

Technically, these could be written as a list of rules that are applied to building ways. Each rule is applied in turn, and if it matches, the default values are set for those tags that don't have explicit values.

One downside of this could be that if the defaults are really good, then people won't notice anything wrong in osmbuildings view and they won't tag the data. :slightly_smiling_face: 

Not sure if this is worth it. Maybe people should just add the tags. I got this idea when I saw relatively tall garages and huts among other buildings that had properly set the levels. They looked rather weird.

Feel free to close this, I don't mind. Just thought I share this.

**Comment by jluttine** [comment]
Ah, found this related issue: https://github.com/OSMBuildings/OSMBuildings/issues/138

**Comment by kekscom** [comment]
Thanks for bringing this up.
Still on our list of server side topics!
