### ISSUE TITLE
which building:shape=* values are possible

### ISSUE THREAD

**Issue by natrius** [OSMBuildings/OSMBuildings#196]
There is currently a discussion in the 3D forum https://forum.openstreetmap.org/viewtopic.php?pid=779930 and i thought i might as you directly: What building:shape=* values are valid and possible as they are already working. If you can tell me that, i may edit the wiki as well and implement this information as well. 

I used it because it was used before and it worked, so i did not question it any further. Or is this some kind of fallback?

**Comment by kekscom** [comment]
Hi, Thank you for taking care of this.
I can't speak for validity as it's a community decision.
For sure we evaluate **building** and **bulding:part** tags as well as several combinations and relations of these.

We do process **building:shape** like:

- cone
- dome
- pyramid (pyramidal accepted too)
- sphere (spherical accepted too)
- none (no building walls rendered, only roof)
- cylinder (cylindrical accepted too)

everything else would be simply extruded

I have no insight why some tagging started working / stopped working.
