### ISSUE TITLE
addOBJ should support valid URLs 

### ISSUE THREAD

**Issue by mryellow** [OSMBuildings/OSMBuildings#198]
Documentation states an *absolute* URL is required.

An absolute URL would be `/path/to/object.obj`

However this fails with `DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL`

Instead a FULL URL is required to bypass this error i.e. `window.location.origin + '/path/to/object.obj'`.

These APIs should support all valid URLs, relative, absolute and full.

**Comment by mryellow** [comment]
Why has no one noticed?

Perhaps this relates to port numbers on local development servers?

Perhaps absolute URLs work on most servers?

**Comment by mryellow** [comment]
People trying to add valid relative URLs:

https://github.com/OSMBuildings/OSMBuildings/issues/160
https://github.com/OSMBuildings/OSMBuildings/issues/174

**Comment by kekscom** [comment]
'Full URLs' would be more precisely.
If you need to create them dynamically, try this:
~~~js
osmb.addOBJ(`${location.protocol}//${location.hostname}/${location.pathname}/Fernsehturm.obj`, { latitude:52.52000, longitude:13.41000 }, { id:'Fernsehturm', scale:1, color:'#ff0000', altitude:0, rotation:51 });
~~~

**Comment by mryellow** [comment]
> (`${location.protocol}//${location.hostname}/${location.pathname}/Fernsehturm.obj`

That should happen behind the scenes when passed a valid URI.
