### ISSUE TITLE
Cannot remove geoJSONTiles layer with destroy()

### ISSUE THREAD

**Issue by grayrattus** [OSMBuildings/OSMBuildings#199]
Hello,

I want to remove previously added geoJSONTiles layer but it doesn't work.
When I check what's inside the layer is see that in its prototype there is `destroy()` function. When I invoke it buildings layer blinks and comes back again.

Is it possible to remove it or toggle its visibility? I'm making an application that uses your library and I need to hide buildings to draw custom polygons. With buildings its also possible but when I put polygon corner inside building its hard to click on it again ;) 

What is interesting I can create working map without `geoJSONTiles` layer and it seems to work fine.

Here is example I made:
```
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.osmbuildings.org/4.0.0/OSMBuildings.css" rel="stylesheet">
    <script src="https://cdn.osmbuildings.org/4.0.0/OSMBuildings.js"></script>
</head>

<body>
    <div style="width: 500px; height: 500px;" id="my-map"></div>
    <button id='remove-layer'>Remove layer</button>
</body>
<script>
    const osmb = new OSMBuildings(
        {
            container: 'my-map',
            position: { latitude: 51.7592, longitude: 19.456 },
            zoom: 16,
            minZoom: 15,
            maxZoom: 22
        });

    osmb.addMapTiles('http://a.tile.stamen.com/toner/{z}/{x}/{y}.png',
        { attribution: '© Data <a href="http://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="http://mapbox.com">Mapbox</a>' });

    const layer = osmb.addGeoJSONTiles('http://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');

    const button = document.querySelector('#remove-layer')
    button.onclick = (ev) => {
        // layer is present
        console.log(layer);
        layer.destroy();
    }
</script>

</html>
```

Also, I really tried to put this example in CodePen or JSFiddle but I got some errors
![image](https://user-images.githubusercontent.com/19289505/77847373-e51e9b00-71bc-11ea-8015-3c499947c45d.png)

So sorry for not providing a remote example. Do you have some JSFIddle with a basic setup that works?

**Comment by kekscom** [comment]
Solved. Re-adding verified too.
You can use these references:
```
<link href="https://cdn.osmbuildings.org/4.0.9/OSMBuildings.css" rel="stylesheet">
<script src="https://cdn.osmbuildings.org/4.0.9/OSMBuildings.js"></script>
```
