### ISSUE TITLE
OL3

### ISSUE THREAD

**Issue by bogdanvaduva** [OSMBuildings/OSMBuildings#2]
I made an example with ol3 (not the best way of doing it but ...):

var osmb = function(map) {
    this.map = map;
    this.maxExtent = [ -20037508.34, -20037508.34, 20037508.34, 20037508.34]; // MaxExtent of layer
    try {
        this.setMap(map);
        map.addLayer(this);
    } catch (e) {
        console.log(e);
    }
};
ol.inherits(osmb, ol.layer.Vector);

var proto = osmb.prototype = ol.layer.Layer ? new  ol.layer.Vector({source: new ol.source.Vector( { projection: ol.proj.get('EPSG:900913') } )}) : { };

proto.setOrigin = function() {
  var map = this.map;
  try {
    var origin = map.getCoordinateFromPixel([0,0]),
    res = map.getView().getResolution(),
    ext = this.maxExtent,
    x = (origin[0] - ext[0]) / res <<0,
    y = (ext[3] - origin[1]) / res <<0;  
    setOrigin({ x:x, y:y });
  } catch (e) {
      console.log(e);
  }
};

proto.setMap = function(map) {
  var scope = this;
  Layers.appendTo(document.getElementById(map.get("target")));
  setSize({ width:map.getSize()[0], height:map.getSize()[1] });

  var layerProjection = this.map.getView().getProjection();
  map.on('click', function(e) {
    var id = HitAreas.getIdFromXY(e.pixel[0], e.pixel[1]);
    if (id) {
      var geo = ol.proj.transform(map.getCoordinateFromPixel([e.pixel[0], e.pixel[1]]),layerProjection, map.getView().getProjection());
      onClick({ feature:id, lat:geo[0], lon:geo[1] });
    }
  });

  map.on('precompose', function(e) {
      setZoom(map.getView().getZoom());
      scope.setOrigin();
      Data.update();
  });

  setZoom(map.getView().getZoom());
  scope.setOrigin();
  Data.update();
};

I hope will help someone :)

**Comment by kekscom** [comment]
Awesome. I'll check it out!

**Comment by bogdanvaduva** [comment]
Hi 
I've changed  a few things. Here the new example:

var osmb = function(map) {
    this.map = map;
    this.maxExtent = [ -20037508.34, -20037508.34, 20037508.34, 20037508.34]; // MaxExtent of layer
    try {
        this.setMap(map);
        map.addLayer(this);
    } catch (e) {
        console.log(e);
    }
};
ol.inherits(osmb, ol.layer.Vector);

var proto = osmb.prototype = ol.layer.Layer ? new  ol.layer.Vector({source: new ol.source.Vector( { projection: ol.proj.get('EPSG:900913') } )}) : { };

proto.setOrigin = function() {
  var map = this.map;
  try {
    var origin = map.getCoordinateFromPixel([0,0]),
    res = map.getView().getResolution(),
    ext = this.maxExtent,
    x = (origin[0] - ext[0]) / res <<0,
    y = (ext[3] - origin[1]) / res <<0;      
    setOrigin({ x:x, y:y });
  } catch (e) {
      console.log(e);
  }
};
                                                                            
proto.setMap = function(map) {
  var scope = this;
  Layers.appendTo(document.getElementById(map.get("target")));
  setSize({ width:map.getSize()[0], height:map.getSize()[1] });

  var layerProjection = this.map.getView().getProjection();
  map.on('click', function(e) {
    var id = HitAreas.getIdFromXY(e.pixel[0], e.pixel[1]);
    if (id) {
      var geo = ol.proj.transform(map.getCoordinateFromPixel([e.pixel[0], e.pixel[1]]),layerProjection, map.getView().getProjection());
      onClick({ feature:id, lat:geo[0], lon:geo[1] });
    }
  });
  
  this.on('precompose', function(e) {
      setZoom(map.getView().getZoom());
      scope.setOrigin();
      Data.resetItems();
      Data.update();
  });
  
};

**Comment by iblancasa** [comment]
Are you thinking in work with OpenLayers 3? It would be a great idea! GLmaps are a good library but OpenLayers can help developers to do more things

**Comment by bogdanvaduva** [comment]
I think this example has been added to the main branch. Unfortunately, it needs some work. 
Once, I have more time I will do it. 
Regards

**Comment by am2222** [comment]
how van we use this to enable OSMbuilding in openlayer3?

**Comment by bogdanvaduva** [comment]
Hi @am2222 

Just copy the example from above. It should work. 

Regards.

**Comment by am2222** [comment]
>Hi @bogdanvaduva ,
thanks..But I have copied all of it to my script tag but does not work, I also added
`var osmb1 = new osmb(map);
//var osmb1 = new OSMBuildings(map).load();`
none of above lines worked, the `var osmb1 = new OSMBuildings(map).load();` also gave me error that `OSMBuildings` is undifined,while I have refrenced OSMBuildings.js in my file, Can you please share an example project?
thanks very much

**Comment by bogdanvaduva** [comment]
Hi @am2222 

I haven't worked with OSMBuildings for an year now. I recommend using https://github.com/bogdanvaduva/osmbuildings because the main API could have changed and in that branch the example works.
Regarding the example I'll be able (hopefully) to post one next week.
Regards.

**Comment by am2222** [comment]
@bogdanvaduva  thanks my friend,I'll try the link you shared,I'll share the result,
thanks very much

**Comment by am2222** [comment]
I've tried a lot but could not get any results, Can some one gives me some hints how to make it work?

**Comment by am2222** [comment]
Any Idea?:(

**Comment by bogdanvaduva** [comment]
Change map.get('target').id to map.getTarget() and there is a character before DATA_SRC
    this.src = src || DATA_SRC.replace('{k}', (key || 'anonymous'));
I've added the example in the archive.

[ol3-example.zip](https://github.com/OSMBuildings/OSMBuildings/files/385342/ol3-example.zip)

**Comment by am2222** [comment]
@bogdanvaduva  thank you so much for your help.It works great now.Any way why it lags?Is it something wrong with openlayer?right?

**Comment by bogdanvaduva** [comment]
I wrote about the lag when I added the example. It's because the way ol3 works and the way buildings overlay it's added. I didn't have time to spend on it. Sorry.
Regards

**Comment by am2222** [comment]
thank you so much for your help and also for time that you have spended  on sample code .Thanks
