### ISSUE TITLE
Zoom limits should be optional and unlimited

### ISSUE THREAD

**Issue by mryellow** [OSMBuildings/OSMBuildings#203]
`maxZoom` and `minZoom` themselves are limited to the values of `MAX_ZOOM` and `MIN_ZOOM`.

Not only are these values used when no `maxZoom` or `minZoom` are defined, but also if those values are outside of the hardcoded range.

https://github.com/OSMBuildings/OSMBuildings/blob/dd64d6a6fd4daac491311aa9c356588d7eaf319a/src/index.js#L78-L79

**Comment by kekscom** [comment]
Yes, this is the intention.

**Comment by mryellow** [comment]
When removing this restrictions I've noticed some strange effects with `zoom`, `12` is okay and then `11` a gap appears at the top. Haven't gone back and investigated deeply but did seem indicative.

Were these limits set based on points where the rendering maths breaks down?

**Comment by kekscom** [comment]
ts among the reasons. There is also no appropriate geojson data source for buildings at these zoom levels yet.
In other words: you would be overloading infrastructure.

**Comment by mryellow** [comment]
Might be possible to default `maxZoom`/`minZoom` on GeoJSON layers while leaving it as optional for others. Creating a situation where buildings stop rendering outside of the range but everything else continues to function.

**Comment by sbourne27** [comment]
I'd upvote the idea of allowing for zoom out while stopping the render on the buildings layer beyond a certain zoom level.  It's a great tool.  Really powerful.  My use case requires being able to start zoomed out at the scale of the city, or even state, and then zooming in to the neighborhood.  It would be fine if the 3D buildings only became active when zoomed into the neighborhood level.

**Comment by kekscom** [comment]
Thank you for raising that and I see your point.
Unfortunately it's out of scope for current version.
