### ISSUE TITLE
Zoom limits should flip when inverted

### ISSUE THREAD

**Issue by mryellow** [OSMBuildings/OSMBuildings#204]
When given `maxZoom` and `minZoom` in reversed order, instead the hardcoded constant values are supplanted in their place.

These values should instead remain as defined but swap.

https://github.com/OSMBuildings/OSMBuildings/blob/dd64d6a6fd4daac491311aa9c356588d7eaf319a/src/index.js#L80-L83

**Comment by kekscom** [comment]
If someone provides invalid values these are simply reset to default.

**Comment by mryellow** [comment]
If the values are numbers which are flipped then the values should be flipped back.

```
 if (this.maxZoom < this.minZoom) { 
   this.minZoom = this.maxZoom; 
   this.maxZoom = this.minZoom; 
 } 
```


Honestly though, this check is redundant if `maxZoom` and `minZoom` are optional instead of limited to hardcoded constants.

**Comment by kekscom** [comment]
What you cite is not the check ins OSM Buildings nor does is create anything meaningful.
