### ISSUE TITLE
Show a door for entrance=yes/main/service

### ISSUE THREAD

**Issue by natrius** [OSMBuildings/OSMBuildings#206]
Just simple model of a door if entrance=yes/main/service/... according to https://wiki.openstreetmap.org/wiki/Key:entrance

So, IF node is on a line && line contains the value building=* THEN show a door. Something like that maybe?

**Comment by kekscom** [comment]
I understand this would be useful and appealing.
Despite the check you describe it's quite some changes in back and fronted.
I'm afraid this would be out of scope.
