### ISSUE TITLE
Only building:parts are rendered

### ISSUE THREAD

**Issue by maro-21** [OSMBuildings/OSMBuildings#209]
I've recently mapped some buildings in 3D but now I can see that they don't render on OSMBuildings:
![buildings1](https://user-images.githubusercontent.com/57260466/83903183-fa381d00-a75d-11ea-8f2c-b83548f51d3b.png)
![buildings2](https://user-images.githubusercontent.com/57260466/83903196-fdcba400-a75d-11ea-809b-b6af58625a89.png)
![buildings3](https://user-images.githubusercontent.com/57260466/83903209-015f2b00-a75e-11ea-8694-0648e566dddb.jpg)

These small parts are tagged:
```
building:part=yes
building:levels=1
```

The whole building is tagged:
```
building=apartments
building:colour=#FFFDD0
building:levels=3
roof:colour=#E96B39
roof:levels=0.5
roof:material=roof_tiles
roof:shape=gabled
```

Is my tagging/geometry wrong or is there something wrong with the renderer?

**Comment by kekscom** [comment]
Could there be a minimal overlap of parts and building? In this case a building is dropped.
In That case a solution would be adding `building:part=yes` to the main part as well.

**Comment by maro-21** [comment]
They have common vertices, I connected building:part to the building.

**Comment by kekscom** [comment]
Could you post the building ID?

**Comment by maro-21** [comment]
https://www.openstreetmap.org/way/100935969
https://www.openstreetmap.org/way/235436825

**Comment by kekscom** [comment]
Thank you.
Building parts are not just touching the main part but are contained entirely.
This will trigger removal of a building which is not declared as part itself.
So far behaviour is as expected.

As soon as you tag building:part to the main element as well everything remains visible.

**Comment by maro-21** [comment]
Is it correct to have `building=*` and `building:part=yes` on one feature?
Osmose triggers such tagging as "suspicious tag combination".

**Comment by kekscom** [comment]
We are not **the** instance to say something is correct or not. Also suspicious doesn't mean incorrect.
You are looking for a way to solve overlapping geometries. Either

1. ignore the case entirely -> bigger part 'swallows' smaller part
2. CSG operation -> smaller part is automatically cut out from bigger part
3. decouple geometries -> remove overlap 
4. tag the dual use feature accordingly -> building + building:part

We're not going to ignore it as in (1) because it is harming major landmarks.
A CSG operation as in (2) is computationally expensive and currently not reasonable to run.
(3) or (4) are on you.

**Comment by maro-21** [comment]
Ok, so to solve this case I'm going to add a missing part, this big building:part which covers the rest of [building=*] and I will move the 3D tags from building to building:part, I hope it will help.

But before I do that, I have a similar question.
You said that if there is an overlap, the main building is dropped.

building: https://www.openstreetmap.org/way/100934368
building:part: https://www.openstreetmap.org/way/798969316
building:part: https://www.openstreetmap.org/way/100933828

reality: 
![building2-reality](https://user-images.githubusercontent.com/57260466/84541466-bca43880-acf7-11ea-91ee-72244a574bd7.png)

OSMBuildings: https://osmbuildings.org/?lat=51.09562&lon=16.94045&zoom=20.0&tilt=30
![building2](https://user-images.githubusercontent.com/57260466/84541485-c5950a00-acf7-11ea-9e98-f6041d93e9a5.png)

I don't understand why this was rendered in that way.
It looks like [this part](https://www.openstreetmap.org/way/798969316) is rendered, we can't see the roof color, but there is a small edge but covered with something else...

It looks like the builing:parts are redered but they are covered with bare building, without any tags.
What can I do to fix this?

**Comment by ghost** [comment]
> Gracias.
> Las piezas de construcción no solo tocan la parte principal, sino que están contenidas por completo.
> Esto provocará la eliminación de un edificio que no está declarado como parte en sí.
> Hasta ahora el comportamiento es el esperado.
> 
> Tan pronto como etiquete building: part al elemento principal, todo permanecerá visible.

False, that's wrong, It is not the expected behavior, the wiki says it can be the way we say, and breaks thousands of cities in Spain for an import that is taking place... you just have to take into account the information of the main building.

It is the renders that must be adapted to the osm database, not osm to them, that's osm's motto...

**Comment by maro-21** [comment]
It works now:
https://osmbuildings.org/?lat=51.09627&lon=16.93672&zoom=19.6&tilt=22
and
https://osmbuildings.org/?lat=51.09563&lon=16.94057&zoom=20.0&tilt=22

I solved it by adding [relation=building](https://www.openstreetmap.org/relation/11790326) in the first case
and in the second case marked it as [building:part=no](https://www.openstreetmap.org/way/100934368).
