### ISSUE TITLE
License of OSMBuilding

### ISSUE THREAD

**Issue by marlo22** [OSMBuildings/OSMBuildings#211]
Hi there :)

I see that in `LICENSE` file is note about some code under GPL license. Does it mean that OSMBuilding is under GPL license (because GPL is viral license) too? Do I must release my application which use OSMBuilding also under GPL?

**Comment by matkoniecz** [comment]
@OSMBuildings - ping?

**Comment by kekscom** [comment]
We specifically do not require you to use OSMBuildings under GPL.
I can't speak for other components.

**Comment by matkoniecz** [comment]
But if you used "Code fragments from osmstreetview" that is "Licensed under the GNU General Public License version 3." ( https://github.com/OSMBuildings/OSMBuildings/blob/master/LICENSE.md ) then you must license entire code under GNU GPL v3

Even using GNU GPL v3 library in general requires you to release code as GNU GPL v3.

https://en.wikipedia.org/wiki/GNU_General_Public_License#Compatibility_and_multi-licensing
