### ISSUE TITLE
osmbuildings.org and models from 3dmr.eu

### ISSUE THREAD

**Issue by Cyrille37** [OSMBuildings/OSMBuildings#215]
Hello,
Thanks for this project, it's really great :-)

Is there a plan to load models from https://3dmr.eu/ into https://osmbuildings.org/ ?

Is they another way to do ? I did not find.

Regards & cheers
Cyrille

**Comment by kekscom** [comment]
Hi Cyrille, 
Thank you for the kind words.
We would love to integrate 3dmr.eu and potentially other sources too.
 Unfortunately there is no capacity to make this happen soon.
Cheers,
Jan

**Comment by Cyrille37** [comment]
Ok, cheers.
