### ISSUE TITLE
Cross Origin Problems with Mapbox

### ISSUE THREAD

**Issue by luisevonderwiese** [OSMBuildings/OSMBuildings#220]
Hey everybody,
I am new to OSM and I was trying to run the example. But I got in trouble with Cross Origin Requests when trying to load the tiles from mapbox, because Access-Control-Allow-Origin need to be set properly. How can I solve this? Thank you for your help!

Here is the code:
```
<!DOCTYPE html>
<head>
  <meta charset="utf-8"/>
</head>
<link href="https://cdn.osmbuildings.org/4.1.1/OSMBuildings.css" rel="stylesheet">
<script src="https://cdn.osmbuildings.org/4.1.1/OSMBuildings.js"></script>

<div id="map" style="position:absolute;height:100%;width:100%"></div>
<script>
  var map = new OSMBuildings({
	container: 'map',
      position: {latitude: 52.514, longitude: 13.35},
      zoom: 17,
      rotation: 0,
      tilt: 40,
	attribution: '© Data <a href="https://openstreetmap.org/copyright/">OpenStreetMap</a> © Map <a href="https://mapbox.com/">Mapbox</a> © 3D <a href="https://osmbuildings.org/copyright/">OSM Buildings</a>'
});



map.addMapTiles('https://{s}.tiles.mapbox.com/v3/[MY_MAPBOX_KEY_HERE]/{z}/{x}/{y}.png');

map.addGeoJSONTiles('https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');
</script>
```

**Comment by kekscom** [comment]
Hi,
You would need a Mapbox API key in oder to use their tiles.
Bitmap tiles seem to be phased out by Mapbox so don't expect too much support.

This page lists alternatives:
https://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by luisevonderwiese** [comment]
Hey Kekscom,
thank you for your help!
At first I found out that I had to disable CORS in my browser for experimenting with local applications.
Further, the Mapbox API changed and requests have to look like:
`map.addMapTiles('https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/{z}/{x}/{y}.png?style=mapbox://styles/mapbox/streets-v11@00&access_token=pk.ey[mapbox_key]');`

Sorry, it was my fault and not really an issue on OSMBuildings...
