### ISSUE TITLE
A whole city broken!

### ISSUE THREAD

**Issue by ghost** [OSMBuildings/OSMBuildings#221]
Hi, you should follow the guidelines of the official osm wiki to represent 3d buildings, otherwise things like this will happen in a whole city: https://osmbuildings.org/?lat=43.36462&lon=-8.40704&zoom=16.0&tilt=36&rotation=-11
All buildings broken!!
This happens because you do not show the parts of the main building if it has building part, and the holes where there is no building:part do not show anything, that is a very serious error that breaks thousands of cities.
You can take note of this 3d map: https://demo.f4map.com/#lat=43.3651919&lon=-8.4084467&zoom=17&camera.theta=52.162&camera.phi=-4.298
This one does take into account all the parameters of the osm wiki, something essential when representing 3d buildings!

**Comment by kekscom** [comment]
You already trolled us on Twitter.
You are claiming to know best how the software works and how to fix things. I still see no pull request.
Also pointing to our commercial competition. How much did you spend exactly to support our work?
I also asked for specific building examples. That's missing since today.
We owe you nothing. Please go away.

**Comment by ghost** [comment]
> Ya nos trolleaste en Twitter.
> Afirma saber mejor cómo funciona el software y cómo arreglar las cosas. Todavía no veo ninguna solicitud de extracción.
> También apuntando a nuestra competencia comercial. ¿Cuánto gastó exactamente para apoyar nuestro trabajo?
> También pedí ejemplos de construcción específicos. Eso falta desde hoy.
> No te debemos nada. Por favor vete.

??????????????????


And this rudeness ??? I am quite surprised and disappointed... It is a bug that we have been commenting on in the Spanish community for a long time, I have no idea of programming, that's what the issues are for, right? At no time have I spoken with bad manners like you just did, the truth is that I have been opening issues for all applications and they have never spoken to me this badly, I demand an apology at least...

Are you talking about trolling? Are you ok? I am not the same person as the other twitter account, the other account is an experienced osm community belonging to the Spanish... And let's not talk about the competition joke, what competition? We are here to learn from everyone, if I am passing you a link of the same location with both applications, the logical thing is that you yourself compare both locations with the two applications, since as you can see, one looks good and the other looks all broken. I was just very sadly surprised by your lack of professionalism speaking that badly of a proposal that is minimal in a 3d map, if the map is not shown, what kind of 3d map is it?
