### ISSUE TITLE
Background is black

### ISSUE THREAD

**Issue by maro-21** [OSMBuildings/OSMBuildings#224]
Streets don't render, there is a black background. What happened?

**Comment by tordanik** [comment]
I suspect this is because OSMBuilding's attempts to request tiles from api.mapbox.com fail with 401 errors. ("Not Authorized - Invalid Token")

**Comment by asier70** [comment]
I like this 3D service and I also noticed this problem..

**Comment by kekscom** [comment]
Hello everyone,
This is connected to Mapbox not sponsoring tiles anymore.
We're going to switch to an alternative asap.

**Comment by natrius** [comment]
Seems like its working now again. Solved? @maro-21 ?

**Comment by asier70** [comment]
I confirm that the backgroud map has been working properly for several days. Thanks!

**Comment by kekscom** [comment]
Yes, we've replaced it with an open OSM style map.
However, this is not an OSM Buildings issue ;-)

**Comment by maro-21** [comment]
Great, thanks!

**Comment by larsurilch** [comment]
Hello guys,

The problem has returned. Does anyone know what it is?! The site example itself has a problem (https://osmbuildings.org)

Thanks

**Comment by natrius** [comment]
Works fine here. Slow internet maybe? Emptied your cache for the site already as well?

**Comment by larsurilch** [comment]
It's back to normal. Thanks.
