### ISSUE TITLE
Potential visual artifacts due to Filter.time()

### ISSUE THREAD

**Issue by rbuch703** [OSMBuildings/OSMBuildings#23]
`Filter.time()` returns the time that has passed since a filter was initialized. This duration is then used for animations. Currently, `Filter.time()` can be called by different `Render` objects to render different parts of the scene for a single frame. In this case it will return **different results** for these individual scene parts during the **same frame** (since time has progressed in-between calls).

This effect is usually unnoticable. But in cases where geometry has to match exactly (e.g. when rendering objects twice to `gl.BLEND` effects), this small difference can lead to visual artifacts.

One solution would be to have a method `Filter.mark()` that is called once every frame and updates an internal variable that holds the updated duration, and replace `Filter.time()` by a method `Filter.frameTime()` that returns the value of that internal variable, thereby returning the same value for each call during an animation frame.

**Comment by kekscom** [comment]
Will be changed.

**Comment by kekscom** [comment]
There are Filter.getTime() and Filter.nextTick()
