### ISSUE TITLE
how could I interact with osm buildings like leaflet

### ISSUE THREAD

**Issue by Byronic94** [OSMBuildings/OSMBuildings#25]
I want to interact with osmBuildings using the leaflet api. Is it posssible? if not, how to bind event to some specific bulidings (not all the buildings)?how to link buildings with geojson data one to one so that I can set different styles(color) of each buildings according to their geojson feature?

**Comment by kekscom** [comment]
For Leaflet support you may want to use the classic 2.5D version of OSM Buildings. https://github.com/kekscom/osmbuildings
To style an individual building use method each()
or for this 3D version:

~~~~map.on('pointermove', function(e) {
  var id = osmb.getTarget(e.x, e.y);
  if (id) {
    osmb.highlight(id, '#f08000');
  } else {
    osmb.highlight(null);
  }
});
~~~

APIs will probably aligned later.
