### ISSUE TITLE
Don't render walls for building=roof

### ISSUE THREAD

**Issue by rbuch703** [OSMBuildings/OSMBuildings#26]
There are quite a number of "buildings" in OSM that do not represent actual buildings, but just free-standing roofs (e.g. http://overpass-turbo.eu/s/d2F). For those buildings tagged as `building`=`roof` OSMBuildings should not attempt to create wall geometry.

(Note: this change would require the building type to be returned in the GeoJSON responses in order to identify those roofs. This is not currently the case).

**Comment by kekscom** [comment]
Done in latest of develop.

**Comment by cwmke** [comment]
This still seems to have issues. I'm noticing that building=roof by seems to render as a [solid building](http://osmbuildings.org/?lat=43.05021&lon=-87.89363&zoom=20&rotation=-30&tilt=16). Is my tagging wrong or is this something else? My expectation is to just show the roof and no walls. For example, a [gas station](http://osmbuildings.org/?lat=43.04879&lon=-87.8967&zoom=20&rotation=-30&tilt=16) with the below tags doesn't show just a roof. Thanks for any help.

amenity=fuel
building:levels=1 (happens with or without this)
building=roof
fuel:diesel=yes
name=Shell

**Comment by kekscom** [comment]
Both should not render walls. Agreed.
building:levels and missing roof shape / roof height don't make sense either.
For reference:
https://www.openstreetmap.org/way/393274981
https://www.openstreetmap.org/way/426873556

**Comment by cwmke** [comment]
Since it's a building=roof, shouldn't building:levels still work for a height? Also, I'll start adding roof shape tags in the future but I would think defaulting to 1 story with roof:shape=flat would be practical for poorly tagged items such as mine ;-).
