### ISSUE TITLE
OSMBuildings.js?

### ISSUE THREAD

**Issue by cesaregerbino** [OSMBuildings/OSMBuildings#29]
Hi all,

in the documentation there is that ".....Link all required libraries in your HTML head section. Files are provided in folder /dist.", but under that folder I can't find this file .... :-(

Suggestion?

Thank you in advance!

**Comment by kekscom** [comment]
Hi,
I need to update the docs. Meanwhile find all built data here: https://github.com/OSMBuildings/OSMBuildings/releases/download/v2.2.1/OSMBuildings-2.2.1.zip
Issue #28 is all about taht question.
