### ISSUE TITLE
Have the ability to load geoJSON straight from a variable as string

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#3]
Currently, addGeoJSON fires a request to read a external file. However, geojson features may be stored in the browser context as a string or JSON. The library should have the ability to pass this string to the addGeoJSON method to render as well.

**Comment by kekscom** [comment]
you should already be able to pass a GeoJSON object as first parameter (instead of url)

**Comment by hrishiballal** [comment]
Hi Jan, 
I tried it but it is creating the Request object to look for the file. When I code below is not working, basically if I put hte geojson in a file, it is putting it but not so when I pass a string. 

<!DOCTYPE html>
<html>
<head>
  <title>OSM Buildings</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <style>
    html, body {
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
    }

    #map {
      width: 100%;
      height: 100%;
    }

    .control {
      position: absolute;
      left: 0;
      z-index: 1000;
    }

    .control.tilt {
      top: 0;
    }

    .control.rotation {
      top: 45px;
    }

    .control.zoom {
      top: 90px;
    }

    .control.zoom button{
      font-weight: normal;
    }

    .control button {
      width: 30px;
      height: 30px;
      margin: 15px 0 0 15px;
      border: 1px solid #999999;
      background: #ffffff;
      opacity: 0.6;
      border-radius: 5px;
      box-shadow: 0 0 5px #666666;
      font-weight: bold;
      text-align: center;
    }

    .control button:hover {
      opacity: 1;
      cursor: pointer;
    }
  </style>
  <script src="OSMBuildings.js"></script>
</head>

<body>
<div id="map"></div>

<div class="control tilt">
  <button class="dec">&#8601;</button>
  <button class="inc">&#8599;</button>
</div>

<div class="control rotation">
  <button class="inc">&#8630;</button>
  <button class="dec">&#8631;</button>
</div>

<div class="control zoom">
  <button class="dec">-</button>
  <button class="inc">+</button>
</div>

<script>
  function positionOnMap(obj) {
    document.addEventListener('keydown', function(e) {
      var transInc = e.altKey ? 0.0002 : 0.00002;
      var rotaInc = e.altKey ? 0.1 : 0.01;
      switch (e.which) {
        case 37: obj.position.longitude -= transInc; break;
        case 39: obj.position.longitude += transInc; break;
        case 38: obj.position.latitude += transInc; break;
        case 40: obj.position.latitude -= transInc; break;
        case 187: obj.scale += rotaInc; break;
        case 189: obj.scale -= rotaInc; break;
        default: return;
      }
      console.log(JSON.stringify({
        position:{
          latitude:parseFloat(obj.position.latitude.toFixed(5)),
          longitude:parseFloat(obj.position.longitude.toFixed(5))
        },
        scale:parseFloat(obj.scale.toFixed(2))
      }));
    });
  }

  //*************************************************************************

  var map = new OSMBuildings('map', {
    position: { latitude:52.52000, longitude:13.41000 },
    baseDir: '.',
    // zoom: 16,
    // rotation: 0, // optional
    // tilt: 0, // optional
    // disabled: true, // disables user input - optional
    minZoom: 14.5,
    maxZoom: 22,
    tileSource: 'http://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
    dataSource: null, // null disables default OSM data,
    showBackfaces: true, // render front and backsides of polygons. false increases performance, true might be needed for bad geometries
    backgroundColor: '#bfb8b0',
    attribution: '© <a href="http://osmbuildings.org/copyright/">OpenStreetMap</a> contributors, Map tiles © <a href="http://mapbox.com">MapBox</a>, 3D © <a href="http://osmbuildings.org">OSM Buildings</a></div>'
  });
  var gj = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
      "height":20,
        "minHeight":-100,
        "color": "rgb(255,200,0)"
        },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              13.409929275512695,
              52.51850591655913
            ],
            [
              13.41331958770752,
              52.517422163556766
            ],
            [
              13.412439823150635,
              52.51627309503224
            ],
            [
              13.409671783447266,
              52.51543738995772
            ],
            [
              13.407247066497803,
              52.515646317716474
            ],
            [
              13.409929275512695,
              52.51850591655913
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
      "height": 0
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              13.404393196105957,
              52.52036651448786
            ],
            [
              13.404393196105957,
              52.52178965550562
            ],
            [
              13.405863046646118,
              52.52178965550562
            ],
            [
              13.405863046646118,
              52.52036651448786
            ],
            [
              13.404393196105957,
              52.52036651448786
            ]
          ]
        ]
      }
    }
  ]
};
  map.addGeoJSON(gj);

</script>
</body>
</html>

**Comment by hrishiballal** [comment]
```javascript
  var gj = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
      "height":20,
        "minHeight":-100,
        "color": "rgb(255,200,0)"
        },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              13.409929275512695,
              52.51850591655913
            ],
            [
              13.41331958770752,
              52.517422163556766
            ],
            [
              13.412439823150635,
              52.51627309503224
            ],
            [
              13.409671783447266,
              52.51543738995772
            ],
            [
              13.407247066497803,
              52.515646317716474
            ],
            [
              13.409929275512695,
              52.51850591655913
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
      "height": 0
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              13.404393196105957,
              52.52036651448786
            ],
            [
              13.404393196105957,
              52.52178965550562
            ],
            [
              13.405863046646118,
              52.52178965550562
            ],
            [
              13.405863046646118,
              52.52036651448786
            ],
            [
              13.404393196105957,
              52.52036651448786
            ]
          ]
        ]
      }
    }
  ]
};
  map.addGeoJSON(gj);
```

**Comment by hrishiballal** [comment]
The code above is not working.

**Comment by kekscom** [comment]
Got it. Give me a moment.

**Comment by kekscom** [comment]
Should be fine now. 

Just introduced some odd texture warnings..

**Comment by hrishiballal** [comment]
:) Testing it, looks fixed. Thank you so much!
