### ISSUE TITLE
Add a LineString GeoJSON

### ISSUE THREAD

**Issue by cesaregerbino** [OSMBuildings/OSMBuildings#30]
Hi,
I've tried to add a GeoJSON (poly) fro some buildings and it's working fine, but I can't add a LineString GeoJSON: I'de like to show the path form two different buildings (I can calculate my path outside, obtaining a path in JSON format). I'ts not possible? I've tried to modify the GeoJSON in the sample transforming it in a LineString GeoJSON but it's not working. Any sample? Thank you in advance!

**Comment by kekscom** [comment]
Hi Cesare, there are various limitations preventing from LineStrings.
I'd recommend to add a buffer around which makes it a polygon. 

AFAIK Turf Buffer is useful: https://github.com/Turfjs/turf-buffer

Hope it helps.

**Comment by cesaregerbino** [comment]
Hi! Following your suggestion I've tried and it's working now .....

Here you're the code (see at bottom ...): I've added the reference to Turf.js and played a bit with JSON data ....Note that my code it's not the bet in the world, I know, but it's working ...).

I hope that could be useful for others ... 

***********************************************

  //********* Remember to put in your script section this reference !!!!!!!! src='https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.2/turf.min.js'>
  //********* 


//This is a sample linestring ......
  var line = {
    "type": "Feature",
    "properties": {},
    "geometry": {
    "type": "LineString",
      "coordinates": [
         [13.409934, 52.51522], 
         [13.410394, 52.515174], 
         [13.410394, 52.515174], 
         [13.410634, 52.516082], 
         [13.410634, 52.516082], 
         [13.410573, 52.516193], 
         [13.410596, 52.516307], 
         [13.410596, 52.516441], 
         [13.410464, 52.516956], 
         [13.410464, 52.516956], 
         [13.412113, 52.51715]    
       ]
    }
  };

  //Set the unit measure and calculate the buffer using Turf.js ....
  var unit = 'meters';
  var buffered = turf.buffer(line, 1, unit);
  var result = turf.featurecollection([buffered]);

  //Convert to string the buffered json ....
  var my_json = JSON.parse(JSON.stringify(result));

  //Create an empty Polygon json to put in OSM Building map ....
  var geojson_route = {
    type: 'FeatureCollection',
     features: [{
      type: 'Feature',
      properties: {
        color: '#FF0080',
        height: 0,
        minHeight: 0
      },
      geometry: {
        type: 'Polygon',
        coordinates: [
          [
          ]
        ]
      }
    }]  
  };  

  //Add the coordinates at the Polygon json bringing them from the buffered json ....
  for (var i = 0; i < my_json.features[0].features[0].geometry.coordinates[0].length; i++) {
      geojson_route.features[0].geometry.coordinates[0][i] = my_json.features[0].features[0].geometry.coordinates[0][i];
  }

  //Add the Polygon json to the map ....
  osmb.addGeoJSON(geojson_route);


***********************************************

The violet "line" in the picture is the path .... 

![osm-building-path](https://cloud.githubusercontent.com/assets/4707083/11927065/f1b170ca-a7c9-11e5-9a7f-d8384b3522e6.PNG)

Thank you very much!

 Cesare

**Comment by kekscom** [comment]
Likewise thank you very much! Never saw the concept in practice.
I've created a CodePen for others to try out things: http://codepen.io/osmbuildings/pen/xZOEaV/
