### ISSUE TITLE
How to add a icon on the map?

### ISSUE THREAD

**Issue by cesaregerbino** [OSMBuildings/OSMBuildings#32]
Hi all,

is there any sample for to add an icon on the map? Could be useful also put a label: I've seen that there is a suggestions but id doesn't work for me ... Could be possibile have a example?

Thanks!

**Comment by kekscom** [comment]
Hi Cesare,
It's not possible for current 3D engine and I'm not sure we will put in the effort soon.
I'd be glad for more background info about your use case.

However we'll be compatible with other base maps soon so there are many more options.

Regards,
Jan

**Comment by cesaregerbino** [comment]
ok, thanks!
