### ISSUE TITLE
Moving label sample (typo error ...)

### ISSUE THREAD

**Issue by cesaregerbino** [OSMBuildings/OSMBuildings#33]
Hi all,

I've notice that there is a typo error in the example about Moving Label at the line 

label.stye.top = Math.round(pos.y) + 'px'; --> error on "stye" !!

The correct one is

label.style.top = Math.round(pos.y) + 'px';

In any case is there a live sample that show how it works?

Thank you!

 Cesare

**Comment by cesaregerbino** [comment]
Solved! There was a my error, so now (after correct the type error above ...) all working fine now!

**Comment by kekscom** [comment]
Typo fixed. Thank you!

Labels are used here: http://interaktiv.morgenpost.de/berlins-neue-skyline/
