### ISSUE TITLE
Change wall color on the fly?

### ISSUE THREAD

**Issue by konzertimpo** [OSMBuildings/OSMBuildings#34]
Hi at all,
is there a way to change the color of one or multiple buildings (e.g. the wall color) by ID from geoJSON data programmatically?

Best regards!

btw: great project!!!

**Comment by kekscom** [comment]
Hi,
there is no proper way yet. You could use highlight(id, color) but need to make sure, relevant buildings share the same id.
If you want this more dynamic, you could work with multiple sets of same buildings (but different colors) and then show() / hide() them as you like.
If you could give more details your use case, we could probably find a much better solution.
Let me know.
Regards
Jan

**Comment by konzertimpo** [comment]
Hi Jan,

thanks for your answer. That's exactly the way I manage it right now (show/hide). But it doesn't seems to be the most elegant way ;)
In my case I would like to do a server side search, return the ids of the "matching" buildings and then highlight / colorize them in the map.

Marco

**Comment by kekscom** [comment]
Hi Marco,

There are some aspects to solve this:

Selection:
- pass a list of id's, or
- allow a filter function which evaluates any building properties  

Modification:
- allow one highlight color: tag each selected building whether it's highlighted or not, or
- allow various colors: don't tag but set explicit colors per building

Things get more complicated when there are multiple - and perhaps conflicting - selections.
Also adding / removing selections can be tricky, especially for objects that are known but not yet loaded.
That often leads to checks that have to be repeated on every rendering step.

I'd appreciate your feedback if you see simplifications here.

**Comment by rbuch703** [comment]
I'd suggest to have a separate getWallColorFunc (or maybe a combined getEntityColorsFunc) callback function that one can optionally pass to the geoJSON parser. That function would get passed the set of all OSM tags/attributes for each feature in turn and would return a color based on these attributes. The current code to obtain the wall and roof colors could be refactored to provide the default implementation for such a callback. But users could easily write their own small function that changes the colors for some features (e.g. based on their OSM id) and uses the default implementation for the rest.

Of course, this approach is not dynamic (you can't quickly change the colors of individual buildings on-demand), but it might cover a sizeable fraction of the use cases with little code change. I'm not sure whether it completely covers @konzertimpo's use case though.

One use case that I have in mind with this solution is helping with OSM editing: one feature that's currently missing in OSMBuildings but would be very useful for OSM contributors is to highlight buildings that are missing certain OSM tags/attributes (most of all building:height/ building:num_levels, but also roof:shape, buildings:material, etc.). With such a callback one could easily write an implementation that sets building colors based on whether these attributes are present.

**Comment by rbuch703** [comment]
@kekscom I just added an example implementation in the staticBuildingColorizer branch.

**Comment by kekscom** [comment]
I've merged your modifier() code.
This should cover majority of cases.
