### ISSUE TITLE
Question about (1) supporting icons (like my_location.png) and (2) text labels

### ISSUE THREAD

**Issue by speechlogger** [OSMBuildings/OSMBuildings#37]
Hi, 
It seems like a great tool, and I would like to know if it supports these 2 features, so as to make it my map engine:
(1) Place png icons on the map
(2) Place text labels on the map. If so, does it keep them facing the user, even if map is rotating?

Thanks

**Comment by kekscom** [comment]
Hi,
You can place icons and text on top of the map with common DOM methods.
Get the correct position in 2D from project(lat, lon, alt) method.

```
  var label = document.getElementById('mylabel');
  map.on('change', function() {
    var pos = osmb.project(52.52, 13.37, 50);
    label.style.left = Math.round(pos.x) + 'px';
    label.style.top = Math.round(pos.y) + 'px';
  });
```

**Comment by konzertimpo** [comment]
Hi speechlogger,

your question should be already answered be the examples ([here](https://github.com/OSMBuildings/OSMBuildings#moving-label))

I've tried it and it's working great.

**Comment by kekscom** [comment]
:+1:
