### ISSUE TITLE
getTarget with added OBJs

### ISSUE THREAD

**Issue by wallb** [OSMBuildings/OSMBuildings#38]
I wanted a pointermove callback when I had the cursor above an added OBJ model. However, I didn't get the OBJ's id (that I had defined in its options) from getTarget().

After some digging it seems to work with a small change in addItems in OBJ.js...
from:
this.data.ids.push(idColor[0], idColor[1], idColor[2], 1);
to:
this.data.ids.push(idColor[0], idColor[1], idColor[2]);

**Comment by kekscom** [comment]
Thank you, well spotted!
I'll push it soon.
