### ISSUE TITLE
Height / Min Height rendering

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#4]
When a min height is assigned and height is set as 0 in geoJSON, the library extrudes the height anyway. Is there a default height associated? 

![screen shot 2015-07-09 at 11 07 44](https://cloud.githubusercontent.com/assets/1588744/8592897/c8ffa41a-262a-11e5-9750-727820cd41f4.png)

**Comment by kekscom** [comment]
Shame on me for the extra late reply.
Yes, there is a min height of about 9 meters.
Some value > 0.0 should fix it.
