### ISSUE TITLE
Needs to support multipolygons

### ISSUE THREAD

**Issue by naoliv** [OSMBuildings/OSMBuildings#40]
It's common to have buildings represented as multipolygons in OSM.
Unfortunatelly OSMBuildings just don't display anything when there are such cases.

Would be good if it could support this.

**Comment by kekscom** [comment]
OSM Buildings does support multipolygons.
Please provide an example of what's not working as expected.

**Comment by naoliv** [comment]
http://www.openstreetmap.org/relation/5553027 isn't displayed, for example: http://osmbuildings.org/?lat=-21.80727&lon=-48.19251&zoom=18&rotation=0&tilt=30

**Comment by kekscom** [comment]
I see. These need to be polygons aka closed areas.

**Comment by naoliv** [comment]
So multipolygons are fully supported?

**Comment by kekscom** [comment]
Maybe not every odd tagging combination. But cases like yours should work.

**Comment by naoliv** [comment]
Closed means it was fixed, will be fixed or won't fix?

**Comment by kekscom** [comment]
Your questiobs are answered.
This is our litetime, please don't waste it.

**Comment by naoliv** [comment]
Then it's a "won't fix" I guess.
F4map properly renders it, by the way:

http://demo.f4map.com/#lat=-21.8072920&lon=-48.1926207&zoom=19
