### ISSUE TITLE
problems with addOBJ 

### ISSUE THREAD

**Issue by konzertimpo** [OSMBuildings/OSMBuildings#41]
Hi,

just downloaded the current Release and tried to add the "Fernsehturm_Berlin.obj" OBJ with the following code found in the git /test/index.html. (obj and material files are exsinting and found)

`osmb.addOBJ('data/Fernsehturm_Berlin.obj', { latitude:52.51941, longitude:13.40445 }, { id:'Fernsehturm', scale:0.095, elevation:8, rotation:51 });`

I get many errors (probably every frame):
**TypeError: a is undefined**
or with the debug.js:
**TypeError: buffer is undefined**

Note: i also removed the osmb.addGeoJSONTiles line.

Please, help ;) !!   ...couldn't find any real example in the web :(

**Comment by kekscom** [comment]
Thanks for reporting!
There was a serious issue with new texturing methods.
It's fixed now. Release: https://github.com/OSMBuildings/OSMBuildings/releases/tag/v2.3.1
