### ISSUE TITLE
slower rendering rate when the viewport is done rendering

### ISSUE THREAD

**Issue by muyueh** [OSMBuildings/OSMBuildings#42]
Will it be possible to slow down the rendering rate once all the buildings are loaded? The CPU loading level seems to remain high, even if not action was taken. (with osmbuildings.com as the only window opened in the browser).

![2016-03-07 8 14 19](https://cloud.githubusercontent.com/assets/1496082/13569240/d7198260-e4a1-11e5-93a8-1d0ea0b3639b.png)
![2016-03-07 8 17 12](https://cloud.githubusercontent.com/assets/1496082/13569241/d725df6a-e4a1-11e5-8548-3eb332b36c4d.png)

cpu profile over a period of 3 minutes on macbook air 
red: "system"; blue: "user"; black: "idle"

Hey people, great job on the project, we used the classic version for our client in telecom.

**Comment by rbuch703** [comment]
Hi @muyueh, currently OSMBuildings will always render at maximum frame rate (browsers usually cap this at 60 fps), even if there are no actual visible differences between the frames. This causes the CPU load you are seeing. So no, it is currently not possible to slow down the rendering rate in times of inactivity.

It wouldn't be too difficult to switch to rendering only changes, but quite a number of source files would need to be changed (every part that *could* introduce a visible change would need to be able to tell if it *would* cause any visible changes if a new frame was drawn). With such a system in place, CPU usage for OSMBuildings would essentially go down to zero whenever the user stops interacting and all the geometry has been loaded and faded in.

Unfortunately, we currently do not have the manpower to focus on this particular feature. But you are very much invited to either contribute code to OSMBuildings to make the necessary changes, or to donate to help fund the development of this particular feature.

**Comment by muyueh** [comment]
@rbuch703 Wow, thank you for your prompt response. I'm willing to try. Can you point to me what is the file/function name that i should be looking for?

**Comment by rbuch703** [comment]
There are a few locations. Most importantly, there is renderFrame() in src/render/index.js:75 (line numbers may differ slightly from version to verson). This method does the actual rendering, and its call to requestAnimationFrame() also schedules the rendering of the respective *next* frame. So you'd have to prevent renderFrame() from calling requestAnimationFrame() *if* no changes were made. You'd also have to implement a mechanism that triggers a requestAnimationFrame() *when* changes are made again that require re-rendering. 

A change can be (I'm not sure if the list is complete):
- a map tile was loaded: src/basemap/tile.js
- a geometry tile was loaded: src/mesh/GeoJSON.js
- the geometry of a newly loaded tile is being faded in: 'filter' in src/mesh/GeoJSON.js
- the user interacts with the map (panning, zooming, rotation)
- the user picks a building (if picking is enabled)
- the camera have been moved by external calls
- the sun position changes while shadow mapping is active

Hope this helps for a start.

**Comment by muyueh** [comment]
I made some tests directly on OSMBuildings.debug.js to to see the preliminary result: 

 http://muyueh.com/30/simGL/vendor/osmbuildings/?lat=52.520000&lon=13.410000&zoom=16.0&tilt=0.0&bend=0.0&rotation=0.0

The idea was to remove requestAnimationFrame, and to call render once whenever there is change (based on the list of above action). This solves the performance problem, yet there may be more elegant way to do it. 

Feedback are welcome.

**Comment by kekscom** [comment]
Yes, rendering once you want it is a way to solve it.
However, your solutions shows the expected results: things get laggy.
Browser can never catch up with a fluid motion and always.

@rbuch703's suggestion is the clean way: keep requestAnimationFrame and check, wheter any relevant position parameter has changed. If not, return early from rendering.

Would be an option for us as well but I can see animated things, i.e. moving cars, water etc. that always renders.

Hope it helped you.

**Comment by wallb** [comment]
I took a stab at implementing what I guess @kekscom meant by 'return early from rendering'.
https://github.com/OSMBuildings/OSMBuildings/compare/develop...wallb:devFrameControl?expand=1

It is disabled by default, so frames will be rendered continuously as before, until FrameControl is enabled.

Pros:
- less fan noise, heat, and battery usage when displaying a static scene.

Cons:
- increased code complexity for a feature that may see limited use
- can't automatically handle changing object properties like the example at: http://osmbuildings.github.io/OSMBuildings/tutorial-Positioning%20a%20map%20object.html

**Comment by kekscom** [comment]
I still like the feature but not sure about implementation.
Perhaps any object + camera could notice about a (renderable) change.
