### ISSUE TITLE
the GLMap test can not run normal

### ISSUE THREAD

**Issue by dyh333** [OSMBuildings/OSMBuildings#43]
hi, i have download the source code but found the GLMap test can not run normal. could you provide a demo code which is same as osmbuilding website? thx.

**Comment by kekscom** [comment]
Hi, for running the source, a full npm install plus a grunt release is required.
All results are placed in dist folder.

You can save the efforts by just downloading the latest release (check github options near file listing).
Hope it helps.

**Comment by dyh333** [comment]
@kekscom thank you very much.
