### ISSUE TITLE
Shadow artifacts

### ISSUE THREAD

**Issue by kekscom** [OSMBuildings/OSMBuildings#46]
From James Conellan

> There are these weird lines on the map. You can see them most clearly in the bottom-right corner of the attached screenshot, where they form a 4-pointed star. They seem to always appear on the map no matter where I look, and no matter what zoom level, rotation, or angle I use. They also show up regardless of what browser I use. I've only seen them recently, so I wonder if this is the result of some recent change in your renderer.

<img src="https://cloud.githubusercontent.com/assets/1887727/13816179/a4d69ea8-eb8d-11e5-8380-a789bb8e1c60.png">

**Comment by kekscom** [comment]
Quick fix would be to turn of shadows entirely. 

There are several measures to fix this which we take step by step next days.

- [ ] disable shadows during night (sun altitude close to 0 or lower)
- [ ] fine tune shadow settings and angles
- [ ] investigate a different mechanism

**Comment by rbuch703** [comment]
Could you re-check whether the issue persists on the current development branch? I replaced the color-coded depth used in SSAO and shadow mapping so far with an actual depth texture. This seems to also have solved some shading mapping issues, but I am not sure whether it solved all of them.

**Comment by kekscom** [comment]
Sold! The changes are awesome in quality and performance.
I love the code cleanup too!

What I noticed:
- console complaint `attempt to bind to invalid uniform "uNormalTransform" in shader "quality building shader"`
- there is worst ever artifacts until you set the date once, i.e. osmb.setDate('2016-06-15 12:30'). After that it works really good

**Comment by rbuch703** [comment]
The first warning is benign. As part of the code cleanup/refactoring, we now get these warnings for the first time - before, invalid uniform assigns would just fail silently. In this one instance, the invalid uniform assign needs to stay there for now, because it is needed by the "performance" building shader, but it will give that warning when the "quality" building shader is used. I'll change the code later to make sure each of the two shaders only gets the uniforms it actually needs.

I'll also look into the new shadow artifacts, I haven't yet tested the code without setting a date.

**Comment by rbuch703** [comment]
Ok, I made some changes to the shadow casting in commits cad0976b2716b941ed83a702d41870a0a1bc0f67 and 2f747f7b6bfe9a3c29de04fd9faaaa6708fdd3fa (branch `develop`). The sun direction computation was broken, causing the sun direction (used e.g. for diffuse lighting) to be inconsistent with the sun view matrix (used for the actual shadow mapping). This inconsistency has caused at least some of the shadow artifacts.

Could you please check whether these changes solve this issue?

**Comment by rbuch703** [comment]
Commit ab6a1062d9317215d51ab6b39beec786e3816034 should fix the *"attempt to bind to invalid uniform"* warnings.

**Comment by kekscom** [comment]
This is so much better.
Thank you!
