### ISSUE TITLE
format of JS3D

### ISSUE THREAD

**Issue by krystalli** [OSMBuildings/OSMBuildings#5]
Hi, the src\formats exists three types(OBJ, GeoJSON, and JS3D). I think JS3D is three.js, but I don't know how to use it. Is it possible use like OBJ and GeoJSON? 

Thanks.

**Comment by kekscom** [comment]
Hi, JS3D is a very customized internal test format.
Please do not use it.

**Comment by krystalli** [comment]
Noted and thank you.
