### ISSUE TITLE
Passing in GeoJSON with Point geometry gives an error

### ISSUE THREAD

**Issue by andybak** [OSMBuildings/OSMBuildings#50]
If your geometry contains something like:

    "geometry": {
        "type": "Point",
        "coordinates": [
            -0.302199,
            50.846629
        ]
    },

you get: GeoJSON.js:176 Uncaught TypeError: Cannot read property '1' of undefined

By comparison Leaflet.js interprets this as a simple marker.

**Comment by kekscom** [comment]
At first I'll handle the error message.
Question is what behavior would you then expect for a point, a 3D marker?

**Comment by andybak** [comment]
> Question is what behavior would you then expect for a point, a 3D marker? 

That's a good question. 

Google maps in 3D mode has a nice 2.5D solution for markers: https://drive.google.com/file/d/0B_afp8i9IOxeU25DRjlLTXJXOHc/view?usp=drivesdk

There's no occlusion behind buildings - which makes sense as tall buildings would hide markers.

**Comment by kekscom** [comment]
Are you sure the error this happens in very latest versions?
There are a few modifications that avoid exactly that.

**Comment by kekscom** [comment]
Error message should be fixed in very last versions of OSM Buildings.
We might go for Points and LineStrings separately later on.

**Comment by kekscom** [comment]
Closing the bug but we keep track of point presentation in #58
