### ISSUE TITLE
How to obtain original GeoJSON from building ID

### ISSUE THREAD

**Issue by matt-deboer** [OSMBuildings/OSMBuildings#56]
Extending from the highlight-building-on-hover example, suppose I want to display some of the original OSM data about that building in a pop-over--is there any easy way to extract the original GeoJSON from which the building was generated? (specifically, I'm trying to recover the 2d polygon from which the building was extruded so I can correlate with other map data)

**Comment by kekscom** [comment]
A good way would be to go with Overpass API.
Once you got the object's ID (i.e. 23853131) you can query like this:

`http://overpass-api.de/api/interpreter?data=[out:json];(relation(23853131);way(r);node(w);way(23853131);way(23853131);node(w));out;`

You'd have to create GeoJSON yourself and relations might be tricky too. But it gets you there.

**Comment by rbuch703** [comment]
@matt-deboer: I'm confused by your question. 

On one hand, you're asking how to retrieve the original OSM data for a buildings. This works the way kekscom describes.

But in your clarification, you mention that you only need the 2d building footprint - and no other OSM data. Now the building footprint (and some but not all OSM attributes) is present in GeoJSON files that OSMBuildings retrieves from the OSMBuildings GeoJSON tile server. You can retrieve those files yourself in the same way from `https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json` in agreement with the terms and services for that tile server. Here, "{s}" can be any of  "a", "b" or "c", "{z}" is "15" for GeoJSON tiles, and you'll have to determine "{x}" and "{y}" based on the building lat/lng and zoom level 15. For the corresponding formulas, see http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames .

**Comment by kekscom** [comment]
Ok, you might calculate the correct tile address, fetch it and iterate over buildings in there.
Not perfect either but true, another way.
You'Re fine to use the service on a fair use basis.

**Comment by matt-deboer** [comment]
Thanks much for the tips -- this suggestion should work just fine for my purposes. 
Ideally, I was looking for a way to avoid duplicating the network traffic (since OSMB has already pulled down the tiles in question). I've added [PR#59](https://github.com/OSMBuildings/OSMBuildings/pull/59) for my suggested change that would allow me to listen for these events...let me know if this makes sense for the project. Thanks.

**Comment by rbuch703** [comment]
@matt-deboer you likely wouldn't duplicate the network traffic, as the browser should cache the GeoJSON file on the first request and serve the second request from the local cache. Nevertheless, your PR seems to be a more elegant way to get the desired information.
