### ISSUE TITLE
Allow Points and LineStrings in GeoJSON

### ISSUE THREAD

**Issue by kekscom** [OSMBuildings/OSMBuildings#58]
Points should be presented as markers. I could imagine a vertical line of defined length + a small spherical element on top.
A billboard representation is another option.

For LineStrings I'd buffer them to Polygons and then display as usual.

Refers to #30 and #50

**Comment by dkniffin** [comment]
I'm gonna work on the points part of this now.

**Comment by kekscom** [comment]
In case you get to LineStrings->Polygon, you may be interested in this Gist https://gist.github.com/kekscom/4194148#file-thick-line-to-polygon-js

**Comment by dkniffin** [comment]
Hmm, so I'm not quite sure how to do this. I thought about doing it like [the moving label example](http://osmbuildings.github.io/OSMBuildings/tutorial-Adding%20a%20moving%20label.html), but I think we'd prefer to do this inside of the render engine, right? I'm not familiar enough with how all that's set up.

**Comment by kekscom** [comment]
You're right, that should be done internally. 
There is another repo doing triangulation work. Here you might add code for Point and LineString: https://github.com/OSMBuildings/Triangulate/blob/master/src/Triangulate.js#L233
If you like to try, I'm glad to assist.

**Comment by ramitix** [comment]
I tried the code in [here](https://github.com/OSMBuildings/OSMBuildings/issues/30#issuecomment-166279075) and I only changed the position of the map and the coordinates,However i can't see the line , any ideas!! 
This is my changes [http://codepen.io/ramitix/pen/JKEwMM]
Thanks

**Comment by ramitix** [comment]
Is it possible to parse MultiLineString to MultiPolyon with turf ?
I tried to play with the code from issue #30 but I don't know how to change the for loop accordingly and Convert to multi string the buffered json..
[http://codepen.io/ramitix/pen/JKEwMM](url)
Thanks

**Comment by kekscom** [comment]
Not currently prioritized.
