### ISSUE TITLE
Feature: Support for clearGeoJSON / clearMesh / clearObj

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#6]
It would be nice to have a helper function that clears existing objects from the map, so for e.g. if geojson or other data is added using the addGeoJSON or addObj , a clearGeoJSON / clearObj will remove them.

**Comment by hrishiballal** [comment]
For the moment I am doing the following: 

```javascript
var addedGJ = map.addGeoJSON(gj);
.
.
addedGJ.destory();
```

**Comment by kekscom** [comment]
Yes, that probably returned because tehre is no reference to meshes anymore.
I've made a step bakc in develop branch. Finally done and cleaned up asap.
