### ISSUE TITLE
OBJ display is corrupted sometimes

### ISSUE THREAD

**Issue by dkniffin** [OSMBuildings/OSMBuildings#62]
I have a 3d model that I'm importing, and it displays wrong sometimes.

Here's an example. Sometimes, the model will show up correctly, like this:
<img width="86" alt="screen shot 2016-04-08 at 6 04 33 pm" src="https://cloud.githubusercontent.com/assets/1680080/14398734/7351aeb6-fdb4-11e5-8fb2-03aefb2b7d8f.png">

And then other times, it will show up like this:
<img width="137" alt="screen shot 2016-04-08 at 6 03 51 pm" src="https://cloud.githubusercontent.com/assets/1680080/14398733/71cf5c28-fdb4-11e5-9f73-23a2bff341bd.png">

I'm not sure what's wrong here. Could it have to do with the number of polygons?

**Comment by kekscom** [comment]
Is this during one session (no reload)?
Model always the same (file unchanged)?

**Comment by dkniffin** [comment]
I refreshed between those pictures. I did not change the files.

**Comment by kekscom** [comment]
Could you send me the OBJ and perhaps your code? Maybe a Codepen...

**Comment by dkniffin** [comment]
[Here's the obj file](https://raw.githubusercontent.com/dkniffin/osm-game/switch-to-osm-buildings/app/assets/models/Dave.obj). The code should be what's on master and I'm calling it like this:

````js
osmb.addOBJ('Dave.obj', { latitude: 35.99179235905418, longitude: -78.90404462814331 }, { id: "character_1", color: 'tan' })
````

**Comment by kekscom** [comment]
Dave is gone :-(
Once revived, I could have a look into this.

**Comment by rbuch703** [comment]
I (presumably) had the same issue today once with the London Eye model. Half of its vertices were shifted about half a kilometer from where they should be. No idea what causes it, though. 

It'd be far easier to debug this on Dave, since he's a much smaller model. But if the London Eye is indeed affected by the same bug, this might at least give us some insights into the common cause.

**Comment by dkniffin** [comment]
@kekscom Fixed the link. Sorry 'bout that. I merged the branch I was working on.

**Comment by dkniffin** [comment]
Also, if it helps, [this](https://raw.githubusercontent.com/dkniffin/osm-game/master/app/assets/models/Zombie_low.obj) is another model that it happens to. Anecdotally, it _seems_ to happen less with this one, but I'm not sure.

**Comment by wallb** [comment]
I've seen distorted geometry when I load more than one OBJ. Fixed it by adding `vertexIndex.length = 0;` in onReady in src/mesh/OBJ.js

**Comment by kekscom** [comment]
Thanks for spotting that!
Now initializing vertexIndex every time.
@dkniffin I didn't test, could you verify?

**Comment by dkniffin** [comment]
@kekscom Yea, I'll test that

**Comment by kekscom** [comment]
Hold back a moment...

**Comment by dkniffin** [comment]
@kekscom When I add that as the first line of onReady, I get `Uncaught TypeError: Cannot set property 'length' of undefined`

**Comment by kekscom** [comment]
Now please. I've changed the code in master accordingly.
Brief tests are fine.

**Comment by dkniffin** [comment]
@kekscom Yep, that fixed it. Thanks @wallb
