### ISSUE TITLE
OSMBuildings.debug.js missing after successful "grunt"

### ISSUE THREAD

**Issue by vikasTmz** [OSMBuildings/OSMBuildings#64]
![grunterror](https://cloud.githubusercontent.com/assets/11690674/14423987/40f6eb4e-fffc-11e5-8afe-9dd921b971bf.png)

Ran 'npm install' , which installed all the dependencies and then ran 'grunt' . Yet I can't find the OSMBuildings.debug.js under dist/OSMBuildings/ .

**Comment by kekscom** [comment]
run `grunt release`
