### ISSUE TITLE
How to obtain the screen bounds of an object by id?

### ISSUE THREAD

**Issue by matt-deboer** [OSMBuildings/OSMBuildings#65]
Suppose I want to display a callout box with some details surrounding a feature, and I want to arrange the callout so that it is close, but not overlapping the 3d object it targets. 

Is there any way to obtain the screen bounds of the object if I know it's ID?

**Comment by kekscom** [comment]
Yes. Not convenient yet but I'm might perhaps be interested in the resulting function.
It's based on osmb.project(lat, lon, alt). Simply iterate over the footprint geometry + height per each point.
That gives you a set of 2d coordinates on screen which you can min/max + offset as you like.

I guess there are more elegant ways but nothing prepared yet.

**Comment by matt-deboer** [comment]
Ok; thanks--that works great. I was actually doing this, but passed lng/lat (reversed) into `project` and was getting bizarre results : )
It's elegant enough for my purposes, especially when only calculating one at a time...

**Comment by dkniffin** [comment]
@matt-deboer If you get something working for this, you should add it as an example to the repo. I'm sure others would like that same functionality (myself included :P)

**Comment by kekscom** [comment]
Yes please, add an example.
I'm closning the "issue" here.

**Comment by matt-deboer** [comment]
I'll add soon; right now, I'm only calculating the bounds of the 2d polygon--need to add the extruded elevation to get an accurate bound.
