### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dkniffin** [OSMBuildings/OSMBuildings#68]
I cleaned up the docs in the readme, but there's still quite a bit of work that could be done. What do you guys think of making a Jekyll site similar to http://leafletjs.com/ with docs, examples, news, etc?

**Comment by kekscom** [comment]
Leaflet has always been a reference to me.
Juts lacking time to set up something properly.
It'd be awesome if you like to help out.

**Comment by dkniffin** [comment]
Cool. I might start working on this soon.

**Comment by dkniffin** [comment]
Right now, I'm thinking of using jsdoc, with [this theme](http://bootswatch.com/united/). Any preference over how we host this doc site? gh-pages? Some other provider?

**Comment by kekscom** [comment]
I'm not sure about hosting. It could blend nicely into the website but nothing ready yet.
Maybe this is another build target later on.

👍 gh-pages + united theme

**Comment by rbuch703** [comment]
The theme looks good. I'd also go with gh-pages. Better to have everything on GitHub for now.

**Comment by dkniffin** [comment]
I've started this on the docs branch, fyi. Feel free to start adding jsdoc style comments to functions, to help out. Otherwise, I'm going to go through all the main functions as I have time, and fill them in.

**Comment by dkniffin** [comment]
@kekscom What's the difference between [addMapTiles](https://github.com/OSMBuildings/OSMBuildings/blob/master/src/index.js#L174) and [addGeoJSONTiles](https://github.com/OSMBuildings/OSMBuildings/blob/master/src/index.js#L167)? It seems like they do almost the same thing.

**Comment by kekscom** [comment]
First adds the basemap (bitmap images below everything), latter adds 3d geometry on top.
Addressing and handling is indeed very similar.

**Comment by dkniffin** [comment]
Oh! I knew that...doh!

**Comment by dkniffin** [comment]
@kekscom Alright, I've almost got gh-pages set up. I'm running into an issue with jsdoc failing because of [prefix.js](https://github.com/OSMBuildings/OSMBuildings/blob/master/src/glx/prefix.js) and [suffix.js](https://github.com/OSMBuildings/OSMBuildings/blob/master/src/glx/suffix.js)

**Comment by kekscom** [comment]
They will not work standalone. The build process combines them to something usable.
You could ignore glx folder for time being and rather take lib/GLX.debug.js instead.
However,  we need to reorganize this.

**Comment by dkniffin** [comment]
Alright, the first push to gh-pages has been made. The site is available here: http://osmbuildings.github.io/OSMBuildings/

I'll be adding more docs in the docs branch for now. When I get all the existing methods documented, and get the site cleaned up the way I want, I'll make a PR.

**Comment by rbuch703** [comment]
Hey, that looks really good. Great work!

**Comment by kekscom** [comment]
Great! It's getting more and more professional.

**Comment by kekscom** [comment]
We might really need running examples somewhere ;-)

**Comment by dkniffin** [comment]
Yea, I was thinking of that. I'm considering making each of those examples [more like Mapbox's](https://www.mapbox.com/mapbox-gl-js/examples/)

**Comment by grayrattus** [comment]
Hello @dkniffin,

I found your documentation 
https://osmbuildings.github.io/OSMBuildings/index.html

and it seems to be outdated with the current 
https://osmbuildings.org/documentation/viewer/api/

Are you still willing to maintain it? If not maybe it's good to make one place with your examples that are still working and put them into this new documentation.

**Comment by kekscom** [comment]
Hi @grayrattus, I'm taking over.
We're all busy with other topics so documentation is what got least dedication.
I'll have a look during next weeks and see what can be updated the simple way.
