### ISSUE TITLE
Better tests

### ISSUE THREAD

**Issue by dkniffin** [OSMBuildings/OSMBuildings#69]
It seems like there are quite a few bugs in this library. I can't help but wonder if some of them are due to it not being properly tested. I haven't ever done front-end tests before, but I know it's possible. [Leaflet has certainly done it](https://github.com/Leaflet/Leaflet/tree/master/spec). What do you guys think about adding tests?

As a side-note, this will probably help with creating comprehensive docs (#68), because API docs can generally be generated from the tests.

**Comment by rbuch703** [comment]
I'm all for (automated) testing, but have no experience with front-end tests either.

**Comment by kekscom** [comment]
All in too. Right now it's just the cluttered html page in /test.
Should be real cases and divided.
I don't feel like setting this up properly, but very happy if you like to help out.

**Comment by dkniffin** [comment]
Cool. I might work on this in addition to documentation (#68)
