### ISSUE TITLE
Disable effects that are not supported by the hardware

### ISSUE THREAD

**Issue by rbuch703** [OSMBuildings/OSMBuildings#76]
Our depth maps (for shadow mapping, SSAO and outlines) are rendered into a depth texture using the `WEBGL_depth_texture` extension. Not all hardware devices support this extension, though. We currently have no fallback, so devices that do not support `WEBGL_depth_texture` cannot use OSMBuildings at all.

Instead, we should simply (silently) disable those effects that are not supported by the underlying hardware.

**Comment by kekscom** [comment]
As long as it's not touching essential functions I'm all for disabling.
As we discussed I the past: use all modern options if reasonably available and only be careful on core things.

**Comment by rbuch703** [comment]
Ok, should be fixed on `develop`. Could you please re-check on that old WIN7 machine with MSIE 11?

**Comment by kekscom** [comment]
Working fine.
