### ISSUE TITLE
Some OSM buildings are not displayed anymore

### ISSUE THREAD

**Issue by trc92** [OSMBuildings/OSMBuildings#77]
Hello guys,

i was setting up an OSMB page for my university and noticed, that some buildings are not displayed anymore. About 3 weeks ago everything was fine but suddenly some structures are missing. This behavior occurs on every tested PC and even on your page (http://osmbuildings.org).

The issue is displayed in the picture below. As you can see some parts of the buildings are missing and remaining objects "fly" in the air. The map from OSM is displayed for comparisons below.
(Coordinates: lat=50.68205&lon=10.93905)

![osmb_issue](https://cloud.githubusercontent.com/assets/18499747/14580881/d66a2850-03dd-11e6-82da-e7098003e760.png)

![osm_issue](https://cloud.githubusercontent.com/assets/18499747/14580909/70302c8c-03de-11e6-8e4b-ab1845b6ac83.png)

Thank you for your time and all possible answers, 

Regards

**Comment by kekscom** [comment]
This is since relation processing got more complex.
Basically buildings in relations are seen as outline, if they intersect with building parts.
And outlines are dropped.

I'll be refining the check to handle different levels.

**Comment by rbuch703** [comment]
@trc92 to elaborate: there are two different reasons that those Building parts are missing, both triggered by a change in the OSMBuildings GeoJSON tile server that better handle building relations.

One reason is that some of those buildings on your campus are mapped incorrectly: The OSM simple building specification (http://wiki.openstreetmap.org/wiki/Simple_3D_buildings) states that if a building (attribute building=\*) overlaps with at least one building part (attribute building:part=\*), then the building should not be rendered. That's what's happening, for example, with the "Zusebau". So here, OSMBuildings is now correctly rendering the data at hand, but the data itself is incorrect. 

The second issue is that the OSMBuildings data server interprets some building relations incorrectly. Building relations (http://wiki.openstreetmap.org/wiki/Relations/Proposed/Buildings) mostly describe which building parts belong to which buildings - but they are also used for indoor mapping. OSMBuildings *should* only interpret the member roles "part" and "outline" of building relations, but seems to also incorrectly consider other member roles. We'll have to fix that.

So the solution is twofold: we'll have to fix the server backend, and you'll have to correctly map the buildings on your campus.

**Comment by kekscom** [comment]
Check for relation role part/outline is fixed on backend.
In case of conflict between building and part, now vertical arrangement is taken into consideration.
This fixes Humboldtbau.
For others you should fix tagging as @rbuch703 suggested.

**Comment by trc92** [comment]
Thank you for your quick fix!

I already looked into the tagging in OSM.
How long will it take for changes to be visible on OSM Building page?

Best regards

**Comment by kekscom** [comment]
Should be visible within an hour.
