### ISSUE TITLE
GLX map catching unbinded click events

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#8]
This a peculiar behaviour I am seeing when using the latest GLX map. When user input is set up as disabled: true  there are no issues. 

However the map seems to be picking up click events unconnected to it when loaded in a container div within a larger page. At every click event the map pans to the right for every click event.

**Comment by kekscom** [comment]
Any chance to see this in action? Codepen, JSFiddle?

**Comment by kekscom** [comment]
Ok found it and fixed. I'll push ASAP.

**Comment by kekscom** [comment]
pushed to master
