### ISSUE TITLE
Add multiple objects at once

### ISSUE THREAD

**Issue by davidkell** [OSMBuildings/OSMBuildings#84]
Trying to add a for loop to add multiple objects at once, from a list of coordinate pairs. (coords)
However it only displays the first object- am I missing something here?

````js
var objs = [];

for (var i = 0, il = coords.length; i < il; i++) {

    obj = osmb.addOBJ('obj/sphere.obj', {longitude: coords[i][0],
                                                 latitude: coords[i][1]},
                                                 {id: i, color: '#0099cc', scale: 50});
  objs.push(obj)
}
````

**Comment by kekscom** [comment]
Technically you're adding the same object here (identified by it's url).
You might vary the file name or maybe some cloning mechanism should be in place.

**Comment by ramitix** [comment]
could you please add an example, still don't work
```
    osmb.addOBJ('./static/images/StopSign.obj', {longitude: -73.981513,latitude: 40.763664},{id: "i22",scale : 100, elevation :-13});
    osmb.addOBJ('./static/images/Sign1.obj', {longitude: -73.983513,latitude: 40.763765},{id: "is23",scale : 100, elevation :-10});
```

**Comment by kekscom** [comment]
Critical thing might be elevation. With your settings, you basically bury the markers :-)
If the problem still exists, could you set up an example on Codepen?
Maybe taking this as a starting point: http://codepen.io/osmbuildings/pen/avXGJy
