### ISSUE TITLE
Export to OBJ

### ISSUE THREAD

**Issue by dkniffin** [OSMBuildings/OSMBuildings#87]
I'm not sure how easy this would be to do, but I'd love to be able to export a view, or maybe a subset of a view, as an obj file. I was reading [this blog post](http://blog.osmbuildings.org/2015/12/3d-print-at-wherecamp-2015_3.html) and thought it might be similar, but the 3d print button doesn't seem to do anything for me. Maybe I'm using it wrong?

**Comment by kekscom** [comment]
You're perfectly right.
Code is already in place but not fully tested. I'll update you asap.

**Comment by sokraticcreations** [comment]
hey @kekscom i was wondering if you had ever finished this feature or are still planning to. i was going to work on something similar on my local repo but figured if you we're close i might as well just wait.

**Comment by kekscom** [comment]
This will not be implemented on client side.
