### ISSUE TITLE
Make IDs in GeoJSON response unique

### ISSUE THREAD

**Issue by rbuch703** [OSMBuildings/OSMBuildings#88]
The OSMBuildings GeoJSON tiles contain an ID for every building. IIRC, this is the way/relation ID from OSM. Now, a unique ID would be very valueable to correctly identify buildings. But as far as I understand, OSMBuildings' IDs are not unique, because OSM uses different ID spaces for ways and relations while OSMBuildings does not. So there can be two unrelated buildings returned from the OSMBuildings server that share the same ID, a multipolygon (via its relation ID) and a building way (via its way ID).

These could be made unique by simply prefixing each ID e.g. with a `w` for ways and an `r` for relations. But this would have to be done on the server side.

**Comment by kekscom** [comment]
done
