### ISSUE TITLE
Remove screenshot.jpg from repository?

### ISSUE THREAD

**Issue by rbuch703** [OSMBuildings/OSMBuildings#89]
Should we remove the screenshot.jpg from the root of the OSMBuildings repository? It's a screenshot from a pretty outdated version of OSMBuildings, and - as I understand it - we aren't using it anywhere anyway (it's not the screenshot used in the documentation).

**Comment by kekscom** [comment]
If it's not used, go ahead.

**Comment by rbuch703** [comment]
alright, done.
