### ISSUE TITLE
No/Bad response from building server

### ISSUE THREAD

**Issue by trc92** [OSMBuildings/OSMBuildings#90]
Hello guys,

i have problems to communicate with the building server since two days ago.
Error messages vary between:

- GET https://d.data.osmbuildings.org/0.2/anonymous/tile/15/17380/11015.json 401 (Unauthorized)
- GET https://c.data.osmbuildings.org/0.2/anonymous/tile/15/17379/11015.json 404 (Not Found)
- Could not parse JSON from https://a.data.osmbuildings.org/0.2/anonymous/tile/15/17380/11016.json
Unexpected token P

I tried to update the OSMBuildings.js file today, but the problems were not fixed. (A new issue "isClockWise is not defined" occured after updating files too).

Best regards

**Comment by kekscom** [comment]
Mostly due to server restrictions.
Solved by mail.

**Comment by ibrahimmohammed1** [comment]
and what could fix this ?!!

**Comment by sandykurniawan19** [comment]
i think , yes. but i want improve

**Comment by kekscom** [comment]
OSM Buildings should be called from a server. Even localhost is fine.
You should also provide a referrer.
These measures are in place because of massive misuse of the backend.
