### ISSUE TITLE
Put a link to the Github repository on the main page

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#91]
In the OSMbuildings.org main page, it is difficult to go to the github repository, a request to put a link to this repo there in the main navigation menu. While I personally don't care too much about a Twitter link but that might be useful to some as well.

**Comment by rbuch703** [comment]
One of the "Fork me on Github" ribbons from https://github.com/blog/273-github-ribbons should do the trick.

**Comment by kekscom** [comment]
Done here now: http://osmbuildings.org/code/
