### ISSUE TITLE
Webpack setup

### ISSUE THREAD

**Issue by radko93** [OSMBuildings/OSMBuildings#92]
`OSMBuildings` installation process really gives me a hard time. Could you give me some clues about configuring OSMBuildings with `Webpack`? This may be helpful. I can make a PR if I make it working later. I know it's more `stackoverflow style` question, but there is almost nothing about installation in `readme`.

**Comment by kekscom** [comment]
What you might need is a distribution pack of OSM Buildings.
Check https://github.com/OSMBuildings/OSMBuildings/releases

**Comment by radko93** [comment]
Any tips about configuring this pack?

**Comment by miszu** [comment]
@radko93 can you please describe in detail what kind of problem you have?

**Comment by radko93** [comment]
I've posted my problem here http://stackoverflow.com/questions/37575797/make-osmbuildings-work-with-webpack-react-and-leaflet

**Comment by kekscom** [comment]
Yes, @moklick tried this in the past.
However, I can't deal with all package managers and frameworks.
I'd recommend to fork and modify https://github.com/OSMBuildings/OSMBuildings/blob/master/src/index.js#L361subsequent lines with code Webpack suggests to make libraries compatible.

**Comment by pducks32** [comment]
I've had the same problem and am trying to figure out the best solution. it seems all the files are being exported to modules but when thee files are concatenated it renders it useless.
