### ISSUE TITLE
Using OSMB with mapbox-gl

### ISSUE THREAD

**Issue by matt-deboer** [OSMBuildings/OSMBuildings#96]
This is more of a question than an issue.
I've been attempting to use OSMB to overlay 3d buildings on top of a mapbox-gl rendered map. The basic idea seems to work (don't load map tiles into GLMap, use a combination of osmb.project and mapbox#fitToBounds to sync up the 2 map views).
The issue seems to be with aligning the 2 perspectives/projections. As you can see from the attached gif,  it looks like the OSMB map is hovering above the mapbox-gl map. From the investigation I've done, it doesn't seem to be a simple zoom issue (as modifying the zoom of the 3d buildings independent of the 2d map doesn't provide a better effect)
![mapbox-osmb](https://cloud.githubusercontent.com/assets/1491381/16243947/8ed5b87e-37ae-11e6-8451-4b2840ee28d9.gif)

I'm just wondering if anyone else has experience with attempting this, and/or looking for any pointers on how to tackle the problem.
Thanks!

**Comment by kekscom** [comment]
Yes, I've tried this a while ago.
It's clearly the wrong approach to use a separate GL view.
Once OSM Buildings is just another rendering pass of MapboxGL, things should run smoothly. Still, handling shadows etc. would be tricky.

Sadly, Mapbox is not really cooperative on this.

**Comment by matt-deboer** [comment]
It looks like they're taking their own stab at this:
https://github.com/mapbox/mapbox-gl-js/issues/684

**Comment by kekscom** [comment]
And it would be a nice combo.

**Comment by kekscom** [comment]
Sadly Mapbox is now competing on this.
There is no point dong their work for free.

**Comment by popovae** [comment]
@kekscom Hi, any update on this? Staying really tuned, but no updates found...maybe I missed something?)

**Comment by kekscom** [comment]
Mapbox is a bit quiet on this and we are busy with a few different topics.
Earliest chance to continue work would be October/November.

**Comment by popovae** [comment]
Hi @kekscom 

Any news on this? Really want to see some mixture of OSM Buildings and Mapbox GL)
I asked Mapbox if they have any plans to give an ability to add OBJ on map and it seems like they are not planing it at all...probably will be able to achieve it using OSM Buildings...

P.S. Any chance anyone can help with "OBJ to Mapbox" - please let me know...really looking for solution!

**Comment by kekscom** [comment]
Hi @popovae 
Thank you for being so patient! I still think it would be a great combination.
But there is no point for us to do it for free and Mapbox taking the profit.

**Comment by popovae** [comment]
Hi @kekscom 
Yes, totally agreed - profitwise probably Mapbox will win much more then OSMB...
I'm following both of the projects for more then a year now and each one has definitely it's pros and cons. At the same time, I see only one thing missing in web cartography for today - one "zoom level" with the maximum details... Abstract 3D buildings are OK for the users on some zoom level, but on the higher zoom I want to see POIs I know or can recognise - Eiffel Tower, St Paul's Cathedral and etc.
This can be achieved only by allowing to add some detailed models to the map - talking LOD1-3
As far as I tried - it can be achieved in OSMB and that is really great! But (sorry, I will be honest) overall OSMB is much slower then Mapbox - they have a better and faster algorithm to draw the abstract 3D buildings (vectors).
So, combining this two technologies - seems the best way to get the best overall user-experiance...unfortunately non of you want to do it along)
Did you ever consider to make a plugin for Mapbox to draw high detailed POIs...probably as a service or a collaborative project like OSM? Something like - anyone can upload there 3D model to your service and put it on the Mapbox with a simple script via API you provide.
Probably Mapbox will do it in a few years themselves, but it is always easier to buy something already existing, then do it from ground up;)

Thank you anyway for reply! Meanwhile will try to find someone who will be able to implement OBJ to Mapbox as a temporary solution for our project)

**Comment by kekscom** [comment]
Focus of both projects is different. MapboxGL is 'just' a map and it does it really nice and fast.
Their buildings are just footprint extrusions without fancy effects.
OSMB focuses on effects and complex models and that makes it a lot slower.

From what I see their engine is not prepared to do more than extrusions.
Enabling it for OBJ would be a major extension.

As said, very interesting but this will set us back for two months while they ramp up competition.
Sadly, at some point this will affect mapping too.

**Comment by popovae** [comment]
@kekscom 
Totally agreed regarding the focus! 
And to be honest - OSMB is the fastest on the market, so "a lot slower" is not quite correct, as comparison should be with Cirsium (don't remember the correct name) and etc!)) So it is a great job you did, really!!!)

> From what I see their engine is not prepared to do more than extrusions.
Enabling it for OBJ would be a major extension.

Not for now for sure. But I don't really see anything difficult for them to implement ability to add OBJ as a source (like images or video) Don't know exactly if they can and plan, can not be competent here, can just assume)

Anyway, thanks to you we nearly found a good temporary solution to draw a more detailed buildings on the Mapbox, need to try to implement it now and probably it will work OK))

**Comment by kekscom** [comment]
If you don't mind, keep me posted about your solution.

**Comment by AlexFactory** [comment]
Hello, is there any solution yet? I'm very curious about this.

**Comment by kekscom** [comment]
**Current state**

We are going to offer Vector Tiles and a Style for Mapbox GL which are more optimized for buildings. Planned release is this week.

We are working on solutions for extended geometry and shadows for Mapbox GL.

There won't be a real OSM Buildings plugin anymore because this can mostly be covered with the other activities.

There are also efforts to expose Mapbox GL's WebGL context which allows a lot more 3D extensions. We are watching this carefully.
