### ISSUE TITLE
 Integrate custom Markers

### ISSUE THREAD

**Issue by ramitix** [OSMBuildings/OSMBuildings#97]
Hi,
Actually, I have some questions not issues.First,
Is it possible to integrate markers and custom markers in Modern 3d version like 2.5D version integrated with  leaflet custom markers  
`var marker_0 = L.marker([40.710425, -74.014572]).addTo(map);`

I also noticed some functions to add layers and add obj, can it be used as a marker and it's scale gets updated according to the map zoom?

Thanks

**Comment by 7dir** [comment]
@ramitix please reopen this issue

**Comment by ramitix** [comment]
I implemented custom markers by using addOBJ "Thanks for @kekscom for enabling OBJ duplicates" and design custom 3d shape as marker, here is the code for that.

```
function plotMarker(){
	
//for loop to  fetch the data from the database	
{% for z in parkZones %}
  	
	//plot 3d object for each location
  	obj = osmb.addOBJ('./static/images/parkzone1.obj', {longitude:{{z.longitude}},latitude: {{z.latitude}} },{id: "marker{{z.id}}" ,scale : 5, elevation :0, rotation : 0 , color: 'red'});
  	markers.push(obj);
	{% endfor %}
	

}
```	

As you can see in the pictures, The marker is the first letter of my logo and I implemented same idea for parking signs.


![screen shot 2017-01-09 at 9 48 25 pm](https://cloud.githubusercontent.com/assets/17752167/21792387/5c7c88dc-d6b7-11e6-9452-15e18d554a4a.png)
![screen shot 2017-01-09 at 9 48 34 pm](https://cloud.githubusercontent.com/assets/17752167/21792384/5c79b9ae-d6b7-11e6-8971-ac396ad1bbfa.png)
![screen shot 2017-01-09 at 10 16 00 pm](https://cloud.githubusercontent.com/assets/17752167/21792651/4360764a-d6b9-11e6-9d56-46da1ecd86f0.png)

Also you can do you custom 2d marker by creating divs and update their location upon movement,  here is the code to implement that.

```
		var dynamicCor = [];
		var dynamicPos = [];

		{% for z in parkZones %}
	  		var pos = osmb.project({{z.latitude}}, {{z.longitude}}, 1);
	  		var cor = {lat:{{z.latitude}},lon:{{z.longitude}}};
	  		
	  		dynamicCor[{{z.id}}]=cor;
	  		dynamicPos[{{z.id}}]=pos;
  		{% endfor %}
	

	 
  		
		osmb.on('change', function() {
	    	for (i=1;i<=dynamicPos.length;i++){
		    	if (document.getElementById('label'+ i)!= null){
		    		dynamicPos[i]= osmb.project(dynamicCor[i].lat, dynamicCor[i].lon, 1);
					document.getElementById('label'+ i).style.left = Math.round(dynamicPos[i].x) + 'px';
				    document.getElementById('label'+ i).style.top = Math.round(dynamicPos[i].y) +60 + 'px';
			  	}

	  		}
		});
```

![screen shot 2017-01-09 at 9 46 52 pm](https://cloud.githubusercontent.com/assets/17752167/21792385/5c7a1e26-d6b7-11e6-8fa4-c0e18398f3d0.png)
![screen shot 2017-01-09 at 9 47 22 pm](https://cloud.githubusercontent.com/assets/17752167/21792386/5c7bd2d4-d6b7-11e6-864d-e6015993c002.png)

Hope that's helpful

**Comment by 7dir** [comment]
@ramitix thanks a lot, but your code not pure js
could you post full example please?

**Comment by ramitix** [comment]
here is the code without the framework code
```
var locations = [];
var  markers = [];
var location_1= {lat:40.764259,lon:-73.984741};
var location_2={lat:40.769234,lon:-73.985741};
//add more locations

locations.pushback(location_1);
locations.pushback(location_2);
////push more location to the array

function plotMarker(){
  for(i=0; i <locations.length;i++){  	
	//plot 3d object for each location
  	 var obj = osmb.addOBJ('./yourDir/your3dObject.obj', {longitude:{{locations[i].lon,latitude:    locations[i].lat },{id: "i" ,scale : 5, elevation :0, rotation : 0 , color: 'red'});
  	markers.push(obj);
	}
}
```
