### ISSUE TITLE
Problems when adding OBJ files

### ISSUE THREAD

**Issue by ramitix** [OSMBuildings/OSMBuildings#98]
I tried some OBJs some of them gives me this problem , any idea..
[Image](https://drive.google.com/file/d/0BzeQyeSTeAy0cFp0LXdDTzI4bjQ/view?usp=sharing)
[Image](https://drive.google.com/file/d/0BzeQyeSTeAy0ekZfZmhZclMzY0k/view?usp=sharing)
[Image](https://drive.google.com/file/d/0BzeQyeSTeAy0MVpxVVlrRXliTzA/view?usp=sharing)
Also is it available to to use material file .mtl for textures?
Thanks

**Comment by kekscom** [comment]
Not all variants of OBJ notation are supported. But most likely yours are not fully valid.
I need a running example to verify.
Textures are not supported yet.

**Comment by ramitix** [comment]
The last OBJ files were edited with blender, however the P shape looks good , The gray stop signs were edited in Microsoft 3d builder.
Is there a recommended program to use for saving OBJ files in the notation that is supported?
What are the supported OBJ notations?
I also read in one of the issues that I can't add the same OBJ with the same url . Is there any way to fix that? 
I am trying to use the OBJs as markers for street parking signs and they are hundreds of them in one view radius so when I use a for loop for the same url "one file" off course it will not work so I tried renaming the file name to add some sort of incrementing mechanism,However I am concerned  about space.
Is it possible to "change the the color "of the added OBJ object by hovering over not Highlighting ?  
Thanks in advance

**Comment by kekscom** [comment]
I can't tell you more about your files structure until I actually see them.
For using same file multiple times, a unique query parameter is sufficient, ie. mysign.obj?1

**Comment by ramitix** [comment]
I uploaded the obj Files [here ](https://drive.google.com/file/d/0BzeQyeSTeAy0REc3TmxuSURLdnM/view?usp=sharing)
regarding the color changing when hover over or click, I tried to use highlight with a green color, however It changes to the default orange . any advice.
 `osmb.highlight(id, '#28A828');`

**Comment by kekscom** [comment]
For the color, initialize like OSMBuildings({ highlightColor:###### })
I'll check the files later on.

**Comment by ramitix** [comment]
Actually, highlight is not effective for color changing .Only the base color get lighter or darker .
Is there a function can be called like `osmb.setColor(id, #####)` instead of highlight?
Thanks For your help.

**Comment by kekscom** [comment]
Alright, I've restored a few things.  `osmb.setColor(id, color)` should work again.

**Comment by ramitix** [comment]
Thanks works great.
> For using same file multiple times, a unique query parameter is sufficient, ie. mysign.obj?1
Could you please elaborate more on unique query parameter ?

**Comment by ramitix** [comment]
Regarding the Obj files, I found that the problem when I export the files from blender I have to convert all the faces to triangles by checking triangulate faces checkbox .
please elaborate more on unique query parameter .
Thanks for your help.

**Comment by kekscom** [comment]
Back from vacation.
I just found what might blocking you from multiple OBJ files.
Query parameter helps but material (MTL) files are an issue.
Without any material info (save without any - not just delete MTL files) it should work.
I'll work on a fix that allows materials again.

**Comment by kekscom** [comment]
Alright, changes done. Check branches master or develop.
