### ISSUE TITLE
Is there any better documentation

### ISSUE THREAD

**Issue by m7vm7v** [OSMBuildings/OSMBuildings#99]
Hi folks. Am I missing something becouse form the provided documentation I can not manage to do anything. So far all in the html is
`<link href="/css/map/OSMBuildings.css" rel="stylesheet" type="text/css"/>
<div id="map" style="z-index: 100; width: 600px; height: 450px;"></div>
<script src="/js/map/OSMBuildings.js" type="text/javascript"></script>`

The JS is : 
` var osmb = new OSMBuildings({
    baseURL: './OSMBuildings',
    minZoom: 13,
    maxZoom: 20,
    position: { latitude:53.4614339, longitude:-3.0042152 },
    zoom: 16,
    highlightColor: '#f08000',
    bounds: {latitude:53.4614339, longitude:-3.0042152},
    tilt: 40,
    effects: ['shadows']
  }).appendTo('map');

  osmb.addMapTiles(
    'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
    {
      attribution: '© Data <a href="https://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="http://mapbox.com">Mapbox</a>'
    }
  );

  osmb.addGeoJSONTiles('https://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');

osmb.addOBJ('sphere.obj', { latitude: 53.4614339, longitude: -3.0042152 }, { id: "my_object_1", color: 'red'});
  //***************************************************************************

  osmb.on('pointermove', function(e) {
    var id = osmb.getTarget(e.detail.x, e.detaily, function(id) {
      if (id) {
        document.body.style.cursor = 'pointer';
        osmb.highlight(id, '#f08000');
      } else {
        document.body.style.cursor = 'default';
        osmb.highlight(null);
      }
    });
  });`

But there is the map only and no sphere created on the place I have pointed. 
Is there some examples how to create just cubes. 
All I need is to create a small map (not moveble so I need some example how to use bounds: object) so I do not need the whole world with all the objects to be rendered ... I need just a small neighborhood fo example and all the rest of the word erased. To place some cubes on the area that if I click on them would show some information. For every single cube a need different color .

Do you think all that would be possible with this library or I should look for something else. 
Any help would be appreciated. Thanks

**Comment by kekscom** [comment]
Hi,
Apologies, I've lost this issue. Is it still valid? Do you have an example somewhere which I could have a look at?
Our documentation can be found here: https://osmbuildings.github.io/OSMBuildings/

From what I see:

Remove this:
`bounds: {latitude:53.4614339, longitude:-3.0042152},`
Fo a static map use `interaction: false`

We've had a typo in `e.detaily`, change it:
`var id = osmb.getTarget(e.detail.x, e.detail.y, function(id) {`

For your sphere/cube there could be many issues like file structure, not triangulated, MTL file missing etc. I need to see it.

You could also try to add GeoJSON. Should be like:
~~~
osmb.addGeoJSON({ type: 'FeatureCollection', features: [
    { type: 'Feature', properties: { color: '#ff0000', roofColor: '#cc0000', height: 50, minHeight: 0 }, geometry:
    { type: 'Polygon', coordinates: [[
      [ -3.00421, 53.46143 ],
      [ -3.00423, 53.46143 ],
      [ -3.00423, 53.46145 ],
      [ -3.00421, 53.46145 ],
      [ -3.00421, 53.46143 ]
    ]] }
    }
  ] })
~~~~
